//! The representation of the external appearance of the device.
//!
//! https://www.bluetooth.com/wp-content/uploads/Files/Specification/Assigned_Numbers.html#bookmark49

// This file is auto-generated by the update_uuids application
// Based on https://bitbucket.org/bluetooth-SIG/public.git

#[allow(dead_code)]
mod categories;

use super::BleUuid;
pub use categories::*;

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_appearance() {
        const UNKNOWN: BleUuid = BleUuid::from_category(0x000, 0x000);
        assert_eq!(u16::from(UNKNOWN), 0x0000);
        let uuid: u16 = UNKNOWN.into();
        assert_eq!(uuid, 0x0000);
        const UUID: [u8; 2] = UNKNOWN.to_le_bytes();
        assert_eq!(UUID, [0x00, 0x00]);
        const GAMEPAD: BleUuid = power_device::GENERIC_POWER_DEVICE;
        assert_eq!(u16::from(GAMEPAD), 0x780);
    }
}
