//! The representation of the external appearance of the device.
//!
//! https://www.bluetooth.com/wp-content/uploads/Files/Specification/Assigned_Numbers.html#bookmark49

// This file is auto-generated by the update_uuids application
// Based on https://bitbucket.org/bluetooth-SIG/public.git

#[allow(dead_code)]
mod categories;

pub use categories::*;

use super::BluetoothUuid16;

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_appearance() {
        const CUSTOM_UUID: BluetoothUuid16 = BluetoothUuid16::from_category(0x002, 0x007);
        assert_eq!(u16::from(CUSTOM_UUID), 0x0087);
        let uuid: u16 = aircraft::LARGE_PASSENGER_AIRCRAFT.into();
        assert_eq!(uuid, 0x0984);
        const LABEL_BYTES: [u8; 2] = signage::ELECTRONIC_LABEL.to_le_bytes();
        assert_eq!(LABEL_BYTES, [0xc2, 0x0a]);
        const GAMEPAD: BluetoothUuid16 = power_device::GENERIC_POWER_DEVICE;
        assert_eq!(u16::from(GAMEPAD), 0x780);
    }
}
