//! UUIDs for the browse group identifiers module.

// This file is auto-generated by the update_uuids application.
// Based on https://bitbucket.org/bluetooth-SIG/public.git
// Commit hash: 43c96bbde30dc6937fba488adb22b6406e1b9cad

use super::BleUuid;

/// Bluetooth browse group identifiers UUID. (0x1002)
pub const PUBLIC_BROWSE_ROOT: BleUuid = BleUuid::new(0x1002);
