//! UUIDs for the characteristic module

// This file is auto-generated by the update_uuids application
// Based on https://bitbucket.org/bluetooth-SIG/public.git

pub(self) use super::BleUuid;

/// Bluetooth characteristic UUID.
pub const DEVICE_NAME: BleUuid = BleUuid::new(0x2a00);

/// Bluetooth characteristic UUID.
pub const APPEARANCE: BleUuid = BleUuid::new(0x2a01);

/// Bluetooth characteristic UUID.
pub const PERIPHERAL_PRIVACY_FLAG: BleUuid = BleUuid::new(0x2a02);

/// Bluetooth characteristic UUID.
pub const RECONNECTION_ADDRESS: BleUuid = BleUuid::new(0x2a03);

/// Bluetooth characteristic UUID.
pub const PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS: BleUuid = BleUuid::new(0x2a04);

/// Bluetooth characteristic UUID.
pub const SERVICE_CHANGED: BleUuid = BleUuid::new(0x2a05);

/// Bluetooth characteristic UUID.
pub const ALERT_LEVEL: BleUuid = BleUuid::new(0x2a06);

/// Bluetooth characteristic UUID.
pub const TX_POWER_LEVEL: BleUuid = BleUuid::new(0x2a07);

/// Bluetooth characteristic UUID.
pub const DATE_TIME: BleUuid = BleUuid::new(0x2a08);

/// Bluetooth characteristic UUID.
pub const DAY_OF_WEEK: BleUuid = BleUuid::new(0x2a09);

/// Bluetooth characteristic UUID.
pub const DAY_DATE_TIME: BleUuid = BleUuid::new(0x2a0a);

/// Bluetooth characteristic UUID.
pub const EXACT_TIME_256: BleUuid = BleUuid::new(0x2a0c);

/// Bluetooth characteristic UUID.
pub const DST_OFFSET: BleUuid = BleUuid::new(0x2a0d);

/// Bluetooth characteristic UUID.
pub const TIME_ZONE: BleUuid = BleUuid::new(0x2a0e);

/// Bluetooth characteristic UUID.
pub const LOCAL_TIME_INFORMATION: BleUuid = BleUuid::new(0x2a0f);

/// Bluetooth characteristic UUID.
pub const TIME_WITH_DST: BleUuid = BleUuid::new(0x2a11);

/// Bluetooth characteristic UUID.
pub const TIME_ACCURACY: BleUuid = BleUuid::new(0x2a12);

/// Bluetooth characteristic UUID.
pub const TIME_SOURCE: BleUuid = BleUuid::new(0x2a13);

/// Bluetooth characteristic UUID.
pub const REFERENCE_TIME_INFORMATION: BleUuid = BleUuid::new(0x2a14);

/// Bluetooth characteristic UUID.
pub const TIME_UPDATE_CONTROL_POINT: BleUuid = BleUuid::new(0x2a16);

/// Bluetooth characteristic UUID.
pub const TIME_UPDATE_STATE: BleUuid = BleUuid::new(0x2a17);

/// Bluetooth characteristic UUID.
pub const GLUCOSE_MEASUREMENT: BleUuid = BleUuid::new(0x2a18);

/// Bluetooth characteristic UUID.
pub const BATTERY_LEVEL: BleUuid = BleUuid::new(0x2a19);

/// Bluetooth characteristic UUID.
pub const TEMPERATURE_MEASUREMENT: BleUuid = BleUuid::new(0x2a1c);

/// Bluetooth characteristic UUID.
pub const TEMPERATURE_TYPE: BleUuid = BleUuid::new(0x2a1d);

/// Bluetooth characteristic UUID.
pub const INTERMEDIATE_TEMPERATURE: BleUuid = BleUuid::new(0x2a1e);

/// Bluetooth characteristic UUID.
pub const MEASUREMENT_INTERVAL: BleUuid = BleUuid::new(0x2a21);

/// Bluetooth characteristic UUID.
pub const BOOT_KEYBOARD_INPUT_REPORT: BleUuid = BleUuid::new(0x2a22);

/// Bluetooth characteristic UUID.
pub const SYSTEM_ID: BleUuid = BleUuid::new(0x2a23);

/// Bluetooth characteristic UUID.
pub const MODEL_NUMBER_STRING: BleUuid = BleUuid::new(0x2a24);

/// Bluetooth characteristic UUID.
pub const SERIAL_NUMBER_STRING: BleUuid = BleUuid::new(0x2a25);

/// Bluetooth characteristic UUID.
pub const FIRMWARE_REVISION_STRING: BleUuid = BleUuid::new(0x2a26);

/// Bluetooth characteristic UUID.
pub const HARDWARE_REVISION_STRING: BleUuid = BleUuid::new(0x2a27);

/// Bluetooth characteristic UUID.
pub const SOFTWARE_REVISION_STRING: BleUuid = BleUuid::new(0x2a28);

/// Bluetooth characteristic UUID.
pub const MANUFACTURER_NAME_STRING: BleUuid = BleUuid::new(0x2a29);

/// Bluetooth characteristic UUID.
pub const IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST: BleUuid = BleUuid::new(0x2a2a);

/// Bluetooth characteristic UUID.
pub const CURRENT_TIME: BleUuid = BleUuid::new(0x2a2b);

/// Bluetooth characteristic UUID.
pub const MAGNETIC_DECLINATION: BleUuid = BleUuid::new(0x2a2c);

/// Bluetooth characteristic UUID.
pub const SCAN_REFRESH: BleUuid = BleUuid::new(0x2a31);

/// Bluetooth characteristic UUID.
pub const BOOT_KEYBOARD_OUTPUT_REPORT: BleUuid = BleUuid::new(0x2a32);

/// Bluetooth characteristic UUID.
pub const BOOT_MOUSE_INPUT_REPORT: BleUuid = BleUuid::new(0x2a33);

/// Bluetooth characteristic UUID.
pub const GLUCOSE_MEASUREMENT_CONTEXT: BleUuid = BleUuid::new(0x2a34);

/// Bluetooth characteristic UUID.
pub const BLOOD_PRESSURE_MEASUREMENT: BleUuid = BleUuid::new(0x2a35);

/// Bluetooth characteristic UUID.
pub const INTERMEDIATE_CUFF_PRESSURE: BleUuid = BleUuid::new(0x2a36);

/// Bluetooth characteristic UUID.
pub const HEART_RATE_MEASUREMENT: BleUuid = BleUuid::new(0x2a37);

/// Bluetooth characteristic UUID.
pub const BODY_SENSOR_LOCATION: BleUuid = BleUuid::new(0x2a38);

/// Bluetooth characteristic UUID.
pub const HEART_RATE_CONTROL_POINT: BleUuid = BleUuid::new(0x2a39);

/// Bluetooth characteristic UUID.
pub const ALERT_STATUS: BleUuid = BleUuid::new(0x2a3f);

/// Bluetooth characteristic UUID.
pub const RINGER_CONTROL_POINT: BleUuid = BleUuid::new(0x2a40);

/// Bluetooth characteristic UUID.
pub const RINGER_SETTING: BleUuid = BleUuid::new(0x2a41);

/// Bluetooth characteristic UUID.
pub const ALERT_CATEGORY_ID_BIT_MASK: BleUuid = BleUuid::new(0x2a42);

/// Bluetooth characteristic UUID.
pub const ALERT_CATEGORY_ID: BleUuid = BleUuid::new(0x2a43);

/// Bluetooth characteristic UUID.
pub const ALERT_NOTIFICATION_CONTROL_POINT: BleUuid = BleUuid::new(0x2a44);

/// Bluetooth characteristic UUID.
pub const UNREAD_ALERT_STATUS: BleUuid = BleUuid::new(0x2a45);

/// Bluetooth characteristic UUID.
pub const NEW_ALERT: BleUuid = BleUuid::new(0x2a46);

/// Bluetooth characteristic UUID.
pub const SUPPORTED_NEW_ALERT_CATEGORY: BleUuid = BleUuid::new(0x2a47);

/// Bluetooth characteristic UUID.
pub const SUPPORTED_UNREAD_ALERT_CATEGORY: BleUuid = BleUuid::new(0x2a48);

/// Bluetooth characteristic UUID.
pub const BLOOD_PRESSURE_FEATURE: BleUuid = BleUuid::new(0x2a49);

/// Bluetooth characteristic UUID.
pub const HID_INFORMATION: BleUuid = BleUuid::new(0x2a4a);

/// Bluetooth characteristic UUID.
pub const REPORT_MAP: BleUuid = BleUuid::new(0x2a4b);

/// Bluetooth characteristic UUID.
pub const HID_CONTROL_POINT: BleUuid = BleUuid::new(0x2a4c);

/// Bluetooth characteristic UUID.
pub const REPORT: BleUuid = BleUuid::new(0x2a4d);

/// Bluetooth characteristic UUID.
pub const PROTOCOL_MODE: BleUuid = BleUuid::new(0x2a4e);

/// Bluetooth characteristic UUID.
pub const SCAN_INTERVAL_WINDOW: BleUuid = BleUuid::new(0x2a4f);

/// Bluetooth characteristic UUID.
pub const PNP_ID: BleUuid = BleUuid::new(0x2a50);

/// Bluetooth characteristic UUID.
pub const GLUCOSE_FEATURE: BleUuid = BleUuid::new(0x2a51);

/// Bluetooth characteristic UUID.
pub const RECORD_ACCESS_CONTROL_POINT: BleUuid = BleUuid::new(0x2a52);

/// Bluetooth characteristic UUID.
pub const RSC_MEASUREMENT: BleUuid = BleUuid::new(0x2a53);

/// Bluetooth characteristic UUID.
pub const RSC_FEATURE: BleUuid = BleUuid::new(0x2a54);

/// Bluetooth characteristic UUID.
pub const SC_CONTROL_POINT: BleUuid = BleUuid::new(0x2a55);

/// Bluetooth characteristic UUID.
pub const AGGREGATE: BleUuid = BleUuid::new(0x2a5a);

/// Bluetooth characteristic UUID.
pub const CSC_MEASUREMENT: BleUuid = BleUuid::new(0x2a5b);

/// Bluetooth characteristic UUID.
pub const CSC_FEATURE: BleUuid = BleUuid::new(0x2a5c);

/// Bluetooth characteristic UUID.
pub const SENSOR_LOCATION: BleUuid = BleUuid::new(0x2a5d);

/// Bluetooth characteristic UUID.
pub const PLX_SPOT_CHECK_MEASUREMENT: BleUuid = BleUuid::new(0x2a5e);

/// Bluetooth characteristic UUID.
pub const PLX_CONTINUOUS_MEASUREMENT: BleUuid = BleUuid::new(0x2a5f);

/// Bluetooth characteristic UUID.
pub const PLX_FEATURES: BleUuid = BleUuid::new(0x2a60);

/// Bluetooth characteristic UUID.
pub const CYCLING_POWER_MEASUREMENT: BleUuid = BleUuid::new(0x2a63);

/// Bluetooth characteristic UUID.
pub const CYCLING_POWER_VECTOR: BleUuid = BleUuid::new(0x2a64);

/// Bluetooth characteristic UUID.
pub const CYCLING_POWER_FEATURE: BleUuid = BleUuid::new(0x2a65);

/// Bluetooth characteristic UUID.
pub const CYCLING_POWER_CONTROL_POINT: BleUuid = BleUuid::new(0x2a66);

/// Bluetooth characteristic UUID.
pub const LOCATION_AND_SPEED: BleUuid = BleUuid::new(0x2a67);

/// Bluetooth characteristic UUID.
pub const NAVIGATION: BleUuid = BleUuid::new(0x2a68);

/// Bluetooth characteristic UUID.
pub const POSITION_QUALITY: BleUuid = BleUuid::new(0x2a69);

/// Bluetooth characteristic UUID.
pub const LN_FEATURE: BleUuid = BleUuid::new(0x2a6a);

/// Bluetooth characteristic UUID.
pub const LN_CONTROL_POINT: BleUuid = BleUuid::new(0x2a6b);

/// Bluetooth characteristic UUID.
pub const ELEVATION: BleUuid = BleUuid::new(0x2a6c);

/// Bluetooth characteristic UUID.
pub const PRESSURE: BleUuid = BleUuid::new(0x2a6d);

/// Bluetooth characteristic UUID.
pub const TEMPERATURE: BleUuid = BleUuid::new(0x2a6e);

/// Bluetooth characteristic UUID.
pub const HUMIDITY: BleUuid = BleUuid::new(0x2a6f);

/// Bluetooth characteristic UUID.
pub const TRUE_WIND_SPEED: BleUuid = BleUuid::new(0x2a70);

/// Bluetooth characteristic UUID.
pub const TRUE_WIND_DIRECTION: BleUuid = BleUuid::new(0x2a71);

/// Bluetooth characteristic UUID.
pub const APPARENT_WIND_SPEED: BleUuid = BleUuid::new(0x2a72);

/// Bluetooth characteristic UUID.
pub const APPARENT_WIND_DIRECTION: BleUuid = BleUuid::new(0x2a73);

/// Bluetooth characteristic UUID.
pub const GUST_FACTOR: BleUuid = BleUuid::new(0x2a74);

/// Bluetooth characteristic UUID.
pub const POLLEN_CONCENTRATION: BleUuid = BleUuid::new(0x2a75);

/// Bluetooth characteristic UUID.
pub const UV_INDEX: BleUuid = BleUuid::new(0x2a76);

/// Bluetooth characteristic UUID.
pub const IRRADIANCE: BleUuid = BleUuid::new(0x2a77);

/// Bluetooth characteristic UUID.
pub const RAINFALL: BleUuid = BleUuid::new(0x2a78);

/// Bluetooth characteristic UUID.
pub const WIND_CHILL: BleUuid = BleUuid::new(0x2a79);

/// Bluetooth characteristic UUID.
pub const HEAT_INDEX: BleUuid = BleUuid::new(0x2a7a);

/// Bluetooth characteristic UUID.
pub const DEW_POINT: BleUuid = BleUuid::new(0x2a7b);

/// Bluetooth characteristic UUID.
pub const DESCRIPTOR_VALUE_CHANGED: BleUuid = BleUuid::new(0x2a7d);

/// Bluetooth characteristic UUID.
pub const AEROBIC_HEART_RATE_LOWER_LIMIT: BleUuid = BleUuid::new(0x2a7e);

/// Bluetooth characteristic UUID.
pub const AEROBIC_THRESHOLD: BleUuid = BleUuid::new(0x2a7f);

/// Bluetooth characteristic UUID.
pub const AGE: BleUuid = BleUuid::new(0x2a80);

/// Bluetooth characteristic UUID.
pub const ANAEROBIC_HEART_RATE_LOWER_LIMIT: BleUuid = BleUuid::new(0x2a81);

/// Bluetooth characteristic UUID.
pub const ANAEROBIC_HEART_RATE_UPPER_LIMIT: BleUuid = BleUuid::new(0x2a82);

/// Bluetooth characteristic UUID.
pub const ANAEROBIC_THRESHOLD: BleUuid = BleUuid::new(0x2a83);

/// Bluetooth characteristic UUID.
pub const AEROBIC_HEART_RATE_UPPER_LIMIT: BleUuid = BleUuid::new(0x2a84);

/// Bluetooth characteristic UUID.
pub const DATE_OF_BIRTH: BleUuid = BleUuid::new(0x2a85);

/// Bluetooth characteristic UUID.
pub const DATE_OF_THRESHOLD_ASSESSMENT: BleUuid = BleUuid::new(0x2a86);

/// Bluetooth characteristic UUID.
pub const EMAIL_ADDRESS: BleUuid = BleUuid::new(0x2a87);

/// Bluetooth characteristic UUID.
pub const FAT_BURN_HEART_RATE_LOWER_LIMIT: BleUuid = BleUuid::new(0x2a88);

/// Bluetooth characteristic UUID.
pub const FAT_BURN_HEART_RATE_UPPER_LIMIT: BleUuid = BleUuid::new(0x2a89);

/// Bluetooth characteristic UUID.
pub const FIRST_NAME: BleUuid = BleUuid::new(0x2a8a);

/// Bluetooth characteristic UUID.
pub const FIVE_ZONE_HEART_RATE_LIMITS: BleUuid = BleUuid::new(0x2a8b);

/// Bluetooth characteristic UUID.
pub const GENDER: BleUuid = BleUuid::new(0x2a8c);

/// Bluetooth characteristic UUID.
pub const HEART_RATE_MAX: BleUuid = BleUuid::new(0x2a8d);

/// Bluetooth characteristic UUID.
pub const HEIGHT: BleUuid = BleUuid::new(0x2a8e);

/// Bluetooth characteristic UUID.
pub const HIP_CIRCUMFERENCE: BleUuid = BleUuid::new(0x2a8f);

/// Bluetooth characteristic UUID.
pub const LAST_NAME: BleUuid = BleUuid::new(0x2a90);

/// Bluetooth characteristic UUID.
pub const MAXIMUM_RECOMMENDED_HEART_RATE: BleUuid = BleUuid::new(0x2a91);

/// Bluetooth characteristic UUID.
pub const RESTING_HEART_RATE: BleUuid = BleUuid::new(0x2a92);

/// Bluetooth characteristic UUID.
pub const SPORT_TYPE_FOR_AEROBIC_AND_ANAEROBIC_THRESHOLDS: BleUuid = BleUuid::new(0x2a93);

/// Bluetooth characteristic UUID.
pub const THREE_ZONE_HEART_RATE_LIMITS: BleUuid = BleUuid::new(0x2a94);

/// Bluetooth characteristic UUID.
pub const TWO_ZONE_HEART_RATE_LIMITS: BleUuid = BleUuid::new(0x2a95);

/// Bluetooth characteristic UUID.
pub const VO2_MAX: BleUuid = BleUuid::new(0x2a96);

/// Bluetooth characteristic UUID.
pub const WAIST_CIRCUMFERENCE: BleUuid = BleUuid::new(0x2a97);

/// Bluetooth characteristic UUID.
pub const WEIGHT: BleUuid = BleUuid::new(0x2a98);

/// Bluetooth characteristic UUID.
pub const DATABASE_CHANGE_INCREMENT: BleUuid = BleUuid::new(0x2a99);

/// Bluetooth characteristic UUID.
pub const USER_INDEX: BleUuid = BleUuid::new(0x2a9a);

/// Bluetooth characteristic UUID.
pub const BODY_COMPOSITION_FEATURE: BleUuid = BleUuid::new(0x2a9b);

/// Bluetooth characteristic UUID.
pub const BODY_COMPOSITION_MEASUREMENT: BleUuid = BleUuid::new(0x2a9c);

/// Bluetooth characteristic UUID.
pub const WEIGHT_MEASUREMENT: BleUuid = BleUuid::new(0x2a9d);

/// Bluetooth characteristic UUID.
pub const WEIGHT_SCALE_FEATURE: BleUuid = BleUuid::new(0x2a9e);

/// Bluetooth characteristic UUID.
pub const USER_CONTROL_POINT: BleUuid = BleUuid::new(0x2a9f);

/// Bluetooth characteristic UUID.
pub const MAGNETIC_FLUX_DENSITY_2D: BleUuid = BleUuid::new(0x2aa0);

/// Bluetooth characteristic UUID.
pub const MAGNETIC_FLUX_DENSITY_3D: BleUuid = BleUuid::new(0x2aa1);

/// Bluetooth characteristic UUID.
pub const LANGUAGE: BleUuid = BleUuid::new(0x2aa2);

/// Bluetooth characteristic UUID.
pub const BAROMETRIC_PRESSURE_TREND: BleUuid = BleUuid::new(0x2aa3);

/// Bluetooth characteristic UUID.
pub const BOND_MANAGEMENT_CONTROL_POINT: BleUuid = BleUuid::new(0x2aa4);

/// Bluetooth characteristic UUID.
pub const BOND_MANAGEMENT_FEATURE: BleUuid = BleUuid::new(0x2aa5);

/// Bluetooth characteristic UUID.
pub const CENTRAL_ADDRESS_RESOLUTION: BleUuid = BleUuid::new(0x2aa6);

/// Bluetooth characteristic UUID.
pub const CGM_MEASUREMENT: BleUuid = BleUuid::new(0x2aa7);

/// Bluetooth characteristic UUID.
pub const CGM_FEATURE: BleUuid = BleUuid::new(0x2aa8);

/// Bluetooth characteristic UUID.
pub const CGM_STATUS: BleUuid = BleUuid::new(0x2aa9);

/// Bluetooth characteristic UUID.
pub const CGM_SESSION_START_TIME: BleUuid = BleUuid::new(0x2aaa);

/// Bluetooth characteristic UUID.
pub const CGM_SESSION_RUN_TIME: BleUuid = BleUuid::new(0x2aab);

/// Bluetooth characteristic UUID.
pub const CGM_SPECIFIC_OPS_CONTROL_POINT: BleUuid = BleUuid::new(0x2aac);

/// Bluetooth characteristic UUID.
pub const INDOOR_POSITIONING_CONFIGURATION: BleUuid = BleUuid::new(0x2aad);

/// Bluetooth characteristic UUID.
pub const LATITUDE: BleUuid = BleUuid::new(0x2aae);

/// Bluetooth characteristic UUID.
pub const LONGITUDE: BleUuid = BleUuid::new(0x2aaf);

/// Bluetooth characteristic UUID.
pub const LOCAL_NORTH_COORDINATE: BleUuid = BleUuid::new(0x2ab0);

/// Bluetooth characteristic UUID.
pub const LOCAL_EAST_COORDINATE: BleUuid = BleUuid::new(0x2ab1);

/// Bluetooth characteristic UUID.
pub const FLOOR_NUMBER: BleUuid = BleUuid::new(0x2ab2);

/// Bluetooth characteristic UUID.
pub const ALTITUDE: BleUuid = BleUuid::new(0x2ab3);

/// Bluetooth characteristic UUID.
pub const UNCERTAINTY: BleUuid = BleUuid::new(0x2ab4);

/// Bluetooth characteristic UUID.
pub const LOCATION_NAME: BleUuid = BleUuid::new(0x2ab5);

/// Bluetooth characteristic UUID.
pub const URI: BleUuid = BleUuid::new(0x2ab6);

/// Bluetooth characteristic UUID.
pub const HTTP_HEADERS: BleUuid = BleUuid::new(0x2ab7);

/// Bluetooth characteristic UUID.
pub const HTTP_STATUS_CODE: BleUuid = BleUuid::new(0x2ab8);

/// Bluetooth characteristic UUID.
pub const HTTP_ENTITY_BODY: BleUuid = BleUuid::new(0x2ab9);

/// Bluetooth characteristic UUID.
pub const HTTP_CONTROL_POINT: BleUuid = BleUuid::new(0x2aba);

/// Bluetooth characteristic UUID.
pub const HTTPS_SECURITY: BleUuid = BleUuid::new(0x2abb);

/// Bluetooth characteristic UUID.
pub const TDS_CONTROL_POINT: BleUuid = BleUuid::new(0x2abc);

/// Bluetooth characteristic UUID.
pub const OTS_FEATURE: BleUuid = BleUuid::new(0x2abd);

/// Bluetooth characteristic UUID.
pub const OBJECT_NAME: BleUuid = BleUuid::new(0x2abe);

/// Bluetooth characteristic UUID.
pub const OBJECT_TYPE: BleUuid = BleUuid::new(0x2abf);

/// Bluetooth characteristic UUID.
pub const OBJECT_SIZE: BleUuid = BleUuid::new(0x2ac0);

/// Bluetooth characteristic UUID.
pub const OBJECT_FIRST_CREATED: BleUuid = BleUuid::new(0x2ac1);

/// Bluetooth characteristic UUID.
pub const OBJECT_LAST_MODIFIED: BleUuid = BleUuid::new(0x2ac2);

/// Bluetooth characteristic UUID.
pub const OBJECT_ID: BleUuid = BleUuid::new(0x2ac3);

/// Bluetooth characteristic UUID.
pub const OBJECT_PROPERTIES: BleUuid = BleUuid::new(0x2ac4);

/// Bluetooth characteristic UUID.
pub const OBJECT_ACTION_CONTROL_POINT: BleUuid = BleUuid::new(0x2ac5);

/// Bluetooth characteristic UUID.
pub const OBJECT_LIST_CONTROL_POINT: BleUuid = BleUuid::new(0x2ac6);

/// Bluetooth characteristic UUID.
pub const OBJECT_LIST_FILTER: BleUuid = BleUuid::new(0x2ac7);

/// Bluetooth characteristic UUID.
pub const OBJECT_CHANGED: BleUuid = BleUuid::new(0x2ac8);

/// Bluetooth characteristic UUID.
pub const RESOLVABLE_PRIVATE_ADDRESS_ONLY: BleUuid = BleUuid::new(0x2ac9);

/// Bluetooth characteristic UUID.
pub const FITNESS_MACHINE_FEATURE: BleUuid = BleUuid::new(0x2acc);

/// Bluetooth characteristic UUID.
pub const TREADMILL_DATA: BleUuid = BleUuid::new(0x2acd);

/// Bluetooth characteristic UUID.
pub const CROSS_TRAINER_DATA: BleUuid = BleUuid::new(0x2ace);

/// Bluetooth characteristic UUID.
pub const STEP_CLIMBER_DATA: BleUuid = BleUuid::new(0x2acf);

/// Bluetooth characteristic UUID.
pub const STAIR_CLIMBER_DATA: BleUuid = BleUuid::new(0x2ad0);

/// Bluetooth characteristic UUID.
pub const ROWER_DATA: BleUuid = BleUuid::new(0x2ad1);

/// Bluetooth characteristic UUID.
pub const INDOOR_BIKE_DATA: BleUuid = BleUuid::new(0x2ad2);

/// Bluetooth characteristic UUID.
pub const TRAINING_STATUS: BleUuid = BleUuid::new(0x2ad3);

/// Bluetooth characteristic UUID.
pub const SUPPORTED_SPEED_RANGE: BleUuid = BleUuid::new(0x2ad4);

/// Bluetooth characteristic UUID.
pub const SUPPORTED_INCLINATION_RANGE: BleUuid = BleUuid::new(0x2ad5);

/// Bluetooth characteristic UUID.
pub const SUPPORTED_RESISTANCE_LEVEL_RANGE: BleUuid = BleUuid::new(0x2ad6);

/// Bluetooth characteristic UUID.
pub const SUPPORTED_HEART_RATE_RANGE: BleUuid = BleUuid::new(0x2ad7);

/// Bluetooth characteristic UUID.
pub const SUPPORTED_POWER_RANGE: BleUuid = BleUuid::new(0x2ad8);

/// Bluetooth characteristic UUID.
pub const FITNESS_MACHINE_CONTROL_POINT: BleUuid = BleUuid::new(0x2ad9);

/// Bluetooth characteristic UUID.
pub const FITNESS_MACHINE_STATUS: BleUuid = BleUuid::new(0x2ada);

/// Bluetooth characteristic UUID.
pub const MESH_PROVISIONING_DATA_IN: BleUuid = BleUuid::new(0x2adb);

/// Bluetooth characteristic UUID.
pub const MESH_PROVISIONING_DATA_OUT: BleUuid = BleUuid::new(0x2adc);

/// Bluetooth characteristic UUID.
pub const MESH_PROXY_DATA_IN: BleUuid = BleUuid::new(0x2add);

/// Bluetooth characteristic UUID.
pub const MESH_PROXY_DATA_OUT: BleUuid = BleUuid::new(0x2ade);

/// Bluetooth characteristic UUID.
pub const AVERAGE_CURRENT: BleUuid = BleUuid::new(0x2ae0);

/// Bluetooth characteristic UUID.
pub const AVERAGE_VOLTAGE: BleUuid = BleUuid::new(0x2ae1);

/// Bluetooth characteristic UUID.
pub const BOOLEAN: BleUuid = BleUuid::new(0x2ae2);

/// Bluetooth characteristic UUID.
pub const CHROMATIC_DISTANCE_FROM_PLANCKIAN: BleUuid = BleUuid::new(0x2ae3);

/// Bluetooth characteristic UUID.
pub const CHROMATICITY_COORDINATES: BleUuid = BleUuid::new(0x2ae4);

/// Bluetooth characteristic UUID.
pub const CHROMATICITY_IN_CCT_AND_DUV_VALUES: BleUuid = BleUuid::new(0x2ae5);

/// Bluetooth characteristic UUID.
pub const CHROMATICITY_TOLERANCE: BleUuid = BleUuid::new(0x2ae6);

/// Bluetooth characteristic UUID.
pub const CIE_133_1995_COLOR_RENDERING_INDEX: BleUuid = BleUuid::new(0x2ae7);

/// Bluetooth characteristic UUID.
pub const COEFFICIENT: BleUuid = BleUuid::new(0x2ae8);

/// Bluetooth characteristic UUID.
pub const CORRELATED_COLOR_TEMPERATURE: BleUuid = BleUuid::new(0x2ae9);

/// Bluetooth characteristic UUID.
pub const COUNT_16: BleUuid = BleUuid::new(0x2aea);

/// Bluetooth characteristic UUID.
pub const COUNT_24: BleUuid = BleUuid::new(0x2aeb);

/// Bluetooth characteristic UUID.
pub const COUNTRY_CODE: BleUuid = BleUuid::new(0x2aec);

/// Bluetooth characteristic UUID.
pub const DATE_UTC: BleUuid = BleUuid::new(0x2aed);

/// Bluetooth characteristic UUID.
pub const ELECTRIC_CURRENT: BleUuid = BleUuid::new(0x2aee);

/// Bluetooth characteristic UUID.
pub const ELECTRIC_CURRENT_RANGE: BleUuid = BleUuid::new(0x2aef);

/// Bluetooth characteristic UUID.
pub const ELECTRIC_CURRENT_SPECIFICATION: BleUuid = BleUuid::new(0x2af0);

/// Bluetooth characteristic UUID.
pub const ELECTRIC_CURRENT_STATISTICS: BleUuid = BleUuid::new(0x2af1);

/// Bluetooth characteristic UUID.
pub const ENERGY: BleUuid = BleUuid::new(0x2af2);

/// Bluetooth characteristic UUID.
pub const ENERGY_IN_A_PERIOD_OF_DAY: BleUuid = BleUuid::new(0x2af3);

/// Bluetooth characteristic UUID.
pub const EVENT_STATISTICS: BleUuid = BleUuid::new(0x2af4);

/// Bluetooth characteristic UUID.
pub const FIXED_STRING_16: BleUuid = BleUuid::new(0x2af5);

/// Bluetooth characteristic UUID.
pub const FIXED_STRING_24: BleUuid = BleUuid::new(0x2af6);

/// Bluetooth characteristic UUID.
pub const FIXED_STRING_36: BleUuid = BleUuid::new(0x2af7);

/// Bluetooth characteristic UUID.
pub const FIXED_STRING_8: BleUuid = BleUuid::new(0x2af8);

/// Bluetooth characteristic UUID.
pub const GENERIC_LEVEL: BleUuid = BleUuid::new(0x2af9);

/// Bluetooth characteristic UUID.
pub const GLOBAL_TRADE_ITEM_NUMBER: BleUuid = BleUuid::new(0x2afa);

/// Bluetooth characteristic UUID.
pub const ILLUMINANCE: BleUuid = BleUuid::new(0x2afb);

/// Bluetooth characteristic UUID.
pub const LUMINOUS_EFFICACY: BleUuid = BleUuid::new(0x2afc);

/// Bluetooth characteristic UUID.
pub const LUMINOUS_ENERGY: BleUuid = BleUuid::new(0x2afd);

/// Bluetooth characteristic UUID.
pub const LUMINOUS_EXPOSURE: BleUuid = BleUuid::new(0x2afe);

/// Bluetooth characteristic UUID.
pub const LUMINOUS_FLUX: BleUuid = BleUuid::new(0x2aff);

/// Bluetooth characteristic UUID.
pub const LUMINOUS_FLUX_RANGE: BleUuid = BleUuid::new(0x2b00);

/// Bluetooth characteristic UUID.
pub const LUMINOUS_INTENSITY: BleUuid = BleUuid::new(0x2b01);

/// Bluetooth characteristic UUID.
pub const MASS_FLOW: BleUuid = BleUuid::new(0x2b02);

/// Bluetooth characteristic UUID.
pub const PERCEIVED_LIGHTNESS: BleUuid = BleUuid::new(0x2b03);

/// Bluetooth characteristic UUID.
pub const PERCENTAGE_8: BleUuid = BleUuid::new(0x2b04);

/// Bluetooth characteristic UUID.
pub const POWER: BleUuid = BleUuid::new(0x2b05);

/// Bluetooth characteristic UUID.
pub const POWER_SPECIFICATION: BleUuid = BleUuid::new(0x2b06);

/// Bluetooth characteristic UUID.
pub const RELATIVE_RUNTIME_IN_A_CURRENT_RANGE: BleUuid = BleUuid::new(0x2b07);

/// Bluetooth characteristic UUID.
pub const RELATIVE_RUNTIME_IN_A_GENERIC_LEVEL_RANGE: BleUuid = BleUuid::new(0x2b08);

/// Bluetooth characteristic UUID.
pub const RELATIVE_VALUE_IN_A_VOLTAGE_RANGE: BleUuid = BleUuid::new(0x2b09);

/// Bluetooth characteristic UUID.
pub const RELATIVE_VALUE_IN_AN_ILLUMINANCE_RANGE: BleUuid = BleUuid::new(0x2b0a);

/// Bluetooth characteristic UUID.
pub const RELATIVE_VALUE_IN_A_PERIOD_OF_DAY: BleUuid = BleUuid::new(0x2b0b);

/// Bluetooth characteristic UUID.
pub const RELATIVE_VALUE_IN_A_TEMPERATURE_RANGE: BleUuid = BleUuid::new(0x2b0c);

/// Bluetooth characteristic UUID.
pub const TEMPERATURE_8: BleUuid = BleUuid::new(0x2b0d);

/// Bluetooth characteristic UUID.
pub const TEMPERATURE_8_IN_A_PERIOD_OF_DAY: BleUuid = BleUuid::new(0x2b0e);

/// Bluetooth characteristic UUID.
pub const TEMPERATURE_8_STATISTICS: BleUuid = BleUuid::new(0x2b0f);

/// Bluetooth characteristic UUID.
pub const TEMPERATURE_RANGE: BleUuid = BleUuid::new(0x2b10);

/// Bluetooth characteristic UUID.
pub const TEMPERATURE_STATISTICS: BleUuid = BleUuid::new(0x2b11);

/// Bluetooth characteristic UUID.
pub const TIME_DECIHOUR_8: BleUuid = BleUuid::new(0x2b12);

/// Bluetooth characteristic UUID.
pub const TIME_EXPONENTIAL_8: BleUuid = BleUuid::new(0x2b13);

/// Bluetooth characteristic UUID.
pub const TIME_HOUR_24: BleUuid = BleUuid::new(0x2b14);

/// Bluetooth characteristic UUID.
pub const TIME_MILLISECOND_24: BleUuid = BleUuid::new(0x2b15);

/// Bluetooth characteristic UUID.
pub const TIME_SECOND_16: BleUuid = BleUuid::new(0x2b16);

/// Bluetooth characteristic UUID.
pub const TIME_SECOND_8: BleUuid = BleUuid::new(0x2b17);

/// Bluetooth characteristic UUID.
pub const VOLTAGE: BleUuid = BleUuid::new(0x2b18);

/// Bluetooth characteristic UUID.
pub const VOLTAGE_SPECIFICATION: BleUuid = BleUuid::new(0x2b19);

/// Bluetooth characteristic UUID.
pub const VOLTAGE_STATISTICS: BleUuid = BleUuid::new(0x2b1a);

/// Bluetooth characteristic UUID.
pub const VOLUME_FLOW: BleUuid = BleUuid::new(0x2b1b);

/// Bluetooth characteristic UUID.
pub const CHROMATICITY_COORDINATE: BleUuid = BleUuid::new(0x2b1c);

/// Bluetooth characteristic UUID.
pub const RC_FEATURE: BleUuid = BleUuid::new(0x2b1d);

/// Bluetooth characteristic UUID.
pub const RC_SETTINGS: BleUuid = BleUuid::new(0x2b1e);

/// Bluetooth characteristic UUID.
pub const RECONNECTION_CONFIGURATION_CONTROL_POINT: BleUuid = BleUuid::new(0x2b1f);

/// Bluetooth characteristic UUID.
pub const IDD_STATUS_CHANGED: BleUuid = BleUuid::new(0x2b20);

/// Bluetooth characteristic UUID.
pub const IDD_STATUS: BleUuid = BleUuid::new(0x2b21);

/// Bluetooth characteristic UUID.
pub const IDD_ANNUNCIATION_STATUS: BleUuid = BleUuid::new(0x2b22);

/// Bluetooth characteristic UUID.
pub const IDD_FEATURES: BleUuid = BleUuid::new(0x2b23);

/// Bluetooth characteristic UUID.
pub const IDD_STATUS_READER_CONTROL_POINT: BleUuid = BleUuid::new(0x2b24);

/// Bluetooth characteristic UUID.
pub const IDD_COMMAND_CONTROL_POINT: BleUuid = BleUuid::new(0x2b25);

/// Bluetooth characteristic UUID.
pub const IDD_COMMAND_DATA: BleUuid = BleUuid::new(0x2b26);

/// Bluetooth characteristic UUID.
pub const IDD_RECORD_ACCESS_CONTROL_POINT: BleUuid = BleUuid::new(0x2b27);

/// Bluetooth characteristic UUID.
pub const IDD_HISTORY_DATA: BleUuid = BleUuid::new(0x2b28);

/// Bluetooth characteristic UUID.
pub const CLIENT_SUPPORTED_FEATURES: BleUuid = BleUuid::new(0x2b29);

/// Bluetooth characteristic UUID.
pub const DATABASE_HASH: BleUuid = BleUuid::new(0x2b2a);

/// Bluetooth characteristic UUID.
pub const BSS_CONTROL_POINT: BleUuid = BleUuid::new(0x2b2b);

/// Bluetooth characteristic UUID.
pub const BSS_RESPONSE: BleUuid = BleUuid::new(0x2b2c);

/// Bluetooth characteristic UUID.
pub const EMERGENCY_ID: BleUuid = BleUuid::new(0x2b2d);

/// Bluetooth characteristic UUID.
pub const EMERGENCY_TEXT: BleUuid = BleUuid::new(0x2b2e);

/// Bluetooth characteristic UUID.
pub const ACS_STATUS: BleUuid = BleUuid::new(0x2b2f);

/// Bluetooth characteristic UUID.
pub const ACS_DATA_IN: BleUuid = BleUuid::new(0x2b30);

/// Bluetooth characteristic UUID.
pub const ACS_DATA_OUT_NOTIFY: BleUuid = BleUuid::new(0x2b31);

/// Bluetooth characteristic UUID.
pub const ACS_DATA_OUT_INDICATE: BleUuid = BleUuid::new(0x2b32);

/// Bluetooth characteristic UUID.
pub const ACS_CONTROL_POINT: BleUuid = BleUuid::new(0x2b33);

/// Bluetooth characteristic UUID.
pub const ENHANCED_BLOOD_PRESSURE_MEASUREMENT: BleUuid = BleUuid::new(0x2b34);

/// Bluetooth characteristic UUID.
pub const ENHANCED_INTERMEDIATE_CUFF_PRESSURE: BleUuid = BleUuid::new(0x2b35);

/// Bluetooth characteristic UUID.
pub const BLOOD_PRESSURE_RECORD: BleUuid = BleUuid::new(0x2b36);

/// Bluetooth characteristic UUID.
pub const REGISTERED_USER: BleUuid = BleUuid::new(0x2b37);

/// Bluetooth characteristic UUID.
pub const BR_EDR_HANDOVER_DATA: BleUuid = BleUuid::new(0x2b38);

/// Bluetooth characteristic UUID.
pub const BLUETOOTH_SIG_DATA: BleUuid = BleUuid::new(0x2b39);

/// Bluetooth characteristic UUID.
pub const SERVER_SUPPORTED_FEATURES: BleUuid = BleUuid::new(0x2b3a);

/// Bluetooth characteristic UUID.
pub const PHYSICAL_ACTIVITY_MONITOR_FEATURES: BleUuid = BleUuid::new(0x2b3b);

/// Bluetooth characteristic UUID.
pub const GENERAL_ACTIVITY_INSTANTANEOUS_DATA: BleUuid = BleUuid::new(0x2b3c);

/// Bluetooth characteristic UUID.
pub const GENERAL_ACTIVITY_SUMMARY_DATA: BleUuid = BleUuid::new(0x2b3d);

/// Bluetooth characteristic UUID.
pub const CARDIORESPIRATORY_ACTIVITY_INSTANTANEOUS_DATA: BleUuid = BleUuid::new(0x2b3e);

/// Bluetooth characteristic UUID.
pub const CARDIORESPIRATORY_ACTIVITY_SUMMARY_DATA: BleUuid = BleUuid::new(0x2b3f);

/// Bluetooth characteristic UUID.
pub const STEP_COUNTER_ACTIVITY_SUMMARY_DATA: BleUuid = BleUuid::new(0x2b40);

/// Bluetooth characteristic UUID.
pub const SLEEP_ACTIVITY_INSTANTANEOUS_DATA: BleUuid = BleUuid::new(0x2b41);

/// Bluetooth characteristic UUID.
pub const SLEEP_ACTIVITY_SUMMARY_DATA: BleUuid = BleUuid::new(0x2b42);

/// Bluetooth characteristic UUID.
pub const PHYSICAL_ACTIVITY_MONITOR_CONTROL_POINT: BleUuid = BleUuid::new(0x2b43);

/// Bluetooth characteristic UUID.
pub const PHYSICAL_ACTIVITY_CURRENT_SESSION: BleUuid = BleUuid::new(0x2b44);

/// Bluetooth characteristic UUID.
pub const PHYSICAL_ACTIVITY_SESSION_DESCRIPTOR: BleUuid = BleUuid::new(0x2b45);

/// Bluetooth characteristic UUID.
pub const PREFERRED_UNITS: BleUuid = BleUuid::new(0x2b46);

/// Bluetooth characteristic UUID.
pub const HIGH_RESOLUTION_HEIGHT: BleUuid = BleUuid::new(0x2b47);

/// Bluetooth characteristic UUID.
pub const MIDDLE_NAME: BleUuid = BleUuid::new(0x2b48);

/// Bluetooth characteristic UUID.
pub const STRIDE_LENGTH: BleUuid = BleUuid::new(0x2b49);

/// Bluetooth characteristic UUID.
pub const HANDEDNESS: BleUuid = BleUuid::new(0x2b4a);

/// Bluetooth characteristic UUID.
pub const DEVICE_WEARING_POSITION: BleUuid = BleUuid::new(0x2b4b);

/// Bluetooth characteristic UUID.
pub const FOUR_ZONE_HEART_RATE_LIMITS: BleUuid = BleUuid::new(0x2b4c);

/// Bluetooth characteristic UUID.
pub const HIGH_INTENSITY_EXERCISE_THRESHOLD: BleUuid = BleUuid::new(0x2b4d);

/// Bluetooth characteristic UUID.
pub const ACTIVITY_GOAL: BleUuid = BleUuid::new(0x2b4e);

/// Bluetooth characteristic UUID.
pub const SEDENTARY_INTERVAL_NOTIFICATION: BleUuid = BleUuid::new(0x2b4f);

/// Bluetooth characteristic UUID.
pub const CALORIC_INTAKE: BleUuid = BleUuid::new(0x2b50);

/// Bluetooth characteristic UUID.
pub const TMAP_ROLE: BleUuid = BleUuid::new(0x2b51);

/// Bluetooth characteristic UUID.
pub const AUDIO_INPUT_STATE: BleUuid = BleUuid::new(0x2b77);

/// Bluetooth characteristic UUID.
pub const GAIN_SETTINGS_ATTRIBUTE: BleUuid = BleUuid::new(0x2b78);

/// Bluetooth characteristic UUID.
pub const AUDIO_INPUT_TYPE: BleUuid = BleUuid::new(0x2b79);

/// Bluetooth characteristic UUID.
pub const AUDIO_INPUT_STATUS: BleUuid = BleUuid::new(0x2b7a);

/// Bluetooth characteristic UUID.
pub const AUDIO_INPUT_CONTROL_POINT: BleUuid = BleUuid::new(0x2b7b);

/// Bluetooth characteristic UUID.
pub const AUDIO_INPUT_DESCRIPTION: BleUuid = BleUuid::new(0x2b7c);

/// Bluetooth characteristic UUID.
pub const VOLUME_STATE: BleUuid = BleUuid::new(0x2b7d);

/// Bluetooth characteristic UUID.
pub const VOLUME_CONTROL_POINT: BleUuid = BleUuid::new(0x2b7e);

/// Bluetooth characteristic UUID.
pub const VOLUME_FLAGS: BleUuid = BleUuid::new(0x2b7f);

/// Bluetooth characteristic UUID.
pub const VOLUME_OFFSET_STATE: BleUuid = BleUuid::new(0x2b80);

/// Bluetooth characteristic UUID.
pub const AUDIO_LOCATION: BleUuid = BleUuid::new(0x2b81);

/// Bluetooth characteristic UUID.
pub const VOLUME_OFFSET_CONTROL_POINT: BleUuid = BleUuid::new(0x2b82);

/// Bluetooth characteristic UUID.
pub const AUDIO_OUTPUT_DESCRIPTION: BleUuid = BleUuid::new(0x2b83);

/// Bluetooth characteristic UUID.
pub const SET_IDENTITY_RESOLVING_KEY: BleUuid = BleUuid::new(0x2b84);

/// Bluetooth characteristic UUID.
pub const COORDINATED_SET_SIZE: BleUuid = BleUuid::new(0x2b85);

/// Bluetooth characteristic UUID.
pub const SET_MEMBER_LOCK: BleUuid = BleUuid::new(0x2b86);

/// Bluetooth characteristic UUID.
pub const SET_MEMBER_RANK: BleUuid = BleUuid::new(0x2b87);

/// Bluetooth characteristic UUID.
pub const ENCRYPTED_DATA_KEY_MATERIAL: BleUuid = BleUuid::new(0x2b88);

/// Bluetooth characteristic UUID.
pub const APPARENT_ENERGY_32: BleUuid = BleUuid::new(0x2b89);

/// Bluetooth characteristic UUID.
pub const APPARENT_POWER: BleUuid = BleUuid::new(0x2b8a);

/// Bluetooth characteristic UUID.
pub const LIVE_HEALTH_OBSERVATIONS: BleUuid = BleUuid::new(0x2b8b);

/// Bluetooth characteristic UUID.
pub const CO2_CONCENTRATION: BleUuid = BleUuid::new(0x2b8c);

/// Bluetooth characteristic UUID.
pub const COSINE_OF_THE_ANGLE: BleUuid = BleUuid::new(0x2b8d);

/// Bluetooth characteristic UUID.
pub const DEVICE_TIME_FEATURE: BleUuid = BleUuid::new(0x2b8e);

/// Bluetooth characteristic UUID.
pub const DEVICE_TIME_PARAMETERS: BleUuid = BleUuid::new(0x2b8f);

/// Bluetooth characteristic UUID.
pub const DEVICE_TIME: BleUuid = BleUuid::new(0x2b90);

/// Bluetooth characteristic UUID.
pub const DEVICE_TIME_CONTROL_POINT: BleUuid = BleUuid::new(0x2b91);

/// Bluetooth characteristic UUID.
pub const TIME_CHANGE_LOG_DATA: BleUuid = BleUuid::new(0x2b92);

/// Bluetooth characteristic UUID.
pub const MEDIA_PLAYER_NAME: BleUuid = BleUuid::new(0x2b93);

/// Bluetooth characteristic UUID.
pub const MEDIA_PLAYER_ICON_OBJECT_ID: BleUuid = BleUuid::new(0x2b94);

/// Bluetooth characteristic UUID.
pub const MEDIA_PLAYER_ICON_URL: BleUuid = BleUuid::new(0x2b95);

/// Bluetooth characteristic UUID.
pub const TRACK_CHANGED: BleUuid = BleUuid::new(0x2b96);

/// Bluetooth characteristic UUID.
pub const TRACK_TITLE: BleUuid = BleUuid::new(0x2b97);

/// Bluetooth characteristic UUID.
pub const TRACK_DURATION: BleUuid = BleUuid::new(0x2b98);

/// Bluetooth characteristic UUID.
pub const TRACK_POSITION: BleUuid = BleUuid::new(0x2b99);

/// Bluetooth characteristic UUID.
pub const PLAYBACK_SPEED: BleUuid = BleUuid::new(0x2b9a);

/// Bluetooth characteristic UUID.
pub const SEEKING_SPEED: BleUuid = BleUuid::new(0x2b9b);

/// Bluetooth characteristic UUID.
pub const CURRENT_TRACK_SEGMENTS_OBJECT_ID: BleUuid = BleUuid::new(0x2b9c);

/// Bluetooth characteristic UUID.
pub const CURRENT_TRACK_OBJECT_ID: BleUuid = BleUuid::new(0x2b9d);

/// Bluetooth characteristic UUID.
pub const NEXT_TRACK_OBJECT_ID: BleUuid = BleUuid::new(0x2b9e);

/// Bluetooth characteristic UUID.
pub const PARENT_GROUP_OBJECT_ID: BleUuid = BleUuid::new(0x2b9f);

/// Bluetooth characteristic UUID.
pub const CURRENT_GROUP_OBJECT_ID: BleUuid = BleUuid::new(0x2ba0);

/// Bluetooth characteristic UUID.
pub const PLAYING_ORDER: BleUuid = BleUuid::new(0x2ba1);

/// Bluetooth characteristic UUID.
pub const PLAYING_ORDERS_SUPPORTED: BleUuid = BleUuid::new(0x2ba2);

/// Bluetooth characteristic UUID.
pub const MEDIA_STATE: BleUuid = BleUuid::new(0x2ba3);

/// Bluetooth characteristic UUID.
pub const MEDIA_CONTROL_POINT: BleUuid = BleUuid::new(0x2ba4);

/// Bluetooth characteristic UUID.
pub const MEDIA_CONTROL_POINT_OPCODES_SUPPORTED: BleUuid = BleUuid::new(0x2ba5);

/// Bluetooth characteristic UUID.
pub const SEARCH_RESULTS_OBJECT_ID: BleUuid = BleUuid::new(0x2ba6);

/// Bluetooth characteristic UUID.
pub const SEARCH_CONTROL_POINT: BleUuid = BleUuid::new(0x2ba7);

/// Bluetooth characteristic UUID.
pub const ENERGY_32: BleUuid = BleUuid::new(0x2ba8);

/// Bluetooth characteristic UUID.
pub const CONSTANT_TONE_EXTENSION_ENABLE: BleUuid = BleUuid::new(0x2bad);

/// Bluetooth characteristic UUID.
pub const ADVERTISING_CONSTANT_TONE_EXTENSION_MINIMUM_LENGTH: BleUuid = BleUuid::new(0x2bae);

/// Bluetooth characteristic UUID.
pub const ADVERTISING_CONSTANT_TONE_EXTENSION_MINIMUM_TRANSMIT_COUNT: BleUuid = BleUuid::new(0x2baf);

/// Bluetooth characteristic UUID.
pub const ADVERTISING_CONSTANT_TONE_EXTENSION_TRANSMIT_DURATION: BleUuid = BleUuid::new(0x2bb0);

/// Bluetooth characteristic UUID.
pub const ADVERTISING_CONSTANT_TONE_EXTENSION_INTERVAL: BleUuid = BleUuid::new(0x2bb1);

/// Bluetooth characteristic UUID.
pub const ADVERTISING_CONSTANT_TONE_EXTENSION_PHY: BleUuid = BleUuid::new(0x2bb2);

/// Bluetooth characteristic UUID.
pub const BEARER_PROVIDER_NAME: BleUuid = BleUuid::new(0x2bb3);

/// Bluetooth characteristic UUID.
pub const BEARER_UCI: BleUuid = BleUuid::new(0x2bb4);

/// Bluetooth characteristic UUID.
pub const BEARER_TECHNOLOGY: BleUuid = BleUuid::new(0x2bb5);

/// Bluetooth characteristic UUID.
pub const BEARER_URI_SCHEMES_SUPPORTED_LIST: BleUuid = BleUuid::new(0x2bb6);

/// Bluetooth characteristic UUID.
pub const BEARER_SIGNAL_STRENGTH: BleUuid = BleUuid::new(0x2bb7);

/// Bluetooth characteristic UUID.
pub const BEARER_SIGNAL_STRENGTH_REPORTING_INTERVAL: BleUuid = BleUuid::new(0x2bb8);

/// Bluetooth characteristic UUID.
pub const BEARER_LIST_CURRENT_CALLS: BleUuid = BleUuid::new(0x2bb9);

/// Bluetooth characteristic UUID.
pub const CONTENT_CONTROL_ID: BleUuid = BleUuid::new(0x2bba);

/// Bluetooth characteristic UUID.
pub const STATUS_FLAGS: BleUuid = BleUuid::new(0x2bbb);

/// Bluetooth characteristic UUID.
pub const INCOMING_CALL_TARGET_BEARER_URI: BleUuid = BleUuid::new(0x2bbc);

/// Bluetooth characteristic UUID.
pub const CALL_STATE: BleUuid = BleUuid::new(0x2bbd);

/// Bluetooth characteristic UUID.
pub const CALL_CONTROL_POINT: BleUuid = BleUuid::new(0x2bbe);

/// Bluetooth characteristic UUID.
pub const CALL_CONTROL_POINT_OPTIONAL_OPCODES: BleUuid = BleUuid::new(0x2bbf);

/// Bluetooth characteristic UUID.
pub const TERMINATION_REASON: BleUuid = BleUuid::new(0x2bc0);

/// Bluetooth characteristic UUID.
pub const INCOMING_CALL: BleUuid = BleUuid::new(0x2bc1);

/// Bluetooth characteristic UUID.
pub const CALL_FRIENDLY_NAME: BleUuid = BleUuid::new(0x2bc2);

/// Bluetooth characteristic UUID.
pub const MUTE: BleUuid = BleUuid::new(0x2bc3);

/// Bluetooth characteristic UUID.
pub const SINK_ASE: BleUuid = BleUuid::new(0x2bc4);

/// Bluetooth characteristic UUID.
pub const SOURCE_ASE: BleUuid = BleUuid::new(0x2bc5);

/// Bluetooth characteristic UUID.
pub const ASE_CONTROL_POINT: BleUuid = BleUuid::new(0x2bc6);

/// Bluetooth characteristic UUID.
pub const BROADCAST_AUDIO_SCAN_CONTROL_POINT: BleUuid = BleUuid::new(0x2bc7);

/// Bluetooth characteristic UUID.
pub const BROADCAST_RECEIVE_STATE: BleUuid = BleUuid::new(0x2bc8);

/// Bluetooth characteristic UUID.
pub const SINK_PAC: BleUuid = BleUuid::new(0x2bc9);

/// Bluetooth characteristic UUID.
pub const SINK_AUDIO_LOCATIONS: BleUuid = BleUuid::new(0x2bca);

/// Bluetooth characteristic UUID.
pub const SOURCE_PAC: BleUuid = BleUuid::new(0x2bcb);

/// Bluetooth characteristic UUID.
pub const SOURCE_AUDIO_LOCATIONS: BleUuid = BleUuid::new(0x2bcc);

/// Bluetooth characteristic UUID.
pub const AVAILABLE_AUDIO_CONTEXTS: BleUuid = BleUuid::new(0x2bcd);

/// Bluetooth characteristic UUID.
pub const SUPPORTED_AUDIO_CONTEXTS: BleUuid = BleUuid::new(0x2bce);

/// Bluetooth characteristic UUID.
pub const AMMONIA_CONCENTRATION: BleUuid = BleUuid::new(0x2bcf);

/// Bluetooth characteristic UUID.
pub const CARBON_MONOXIDE_CONCENTRATION: BleUuid = BleUuid::new(0x2bd0);

/// Bluetooth characteristic UUID.
pub const METHANE_CONCENTRATION: BleUuid = BleUuid::new(0x2bd1);

/// Bluetooth characteristic UUID.
pub const NITROGEN_DIOXIDE_CONCENTRATION: BleUuid = BleUuid::new(0x2bd2);

/// Bluetooth characteristic UUID.
pub const NON_METHANE_VOLATILE_ORGANIC_COMPOUNDS_CONCENTRATION: BleUuid = BleUuid::new(0x2bd3);

/// Bluetooth characteristic UUID.
pub const OZONE_CONCENTRATION: BleUuid = BleUuid::new(0x2bd4);

/// Bluetooth characteristic UUID.
pub const PARTICULATE_MATTER_PM1_CONCENTRATION: BleUuid = BleUuid::new(0x2bd5);

/// Bluetooth characteristic UUID.
pub const PARTICULATE_MATTER_PM25_CONCENTRATION: BleUuid = BleUuid::new(0x2bd6);

/// Bluetooth characteristic UUID.
pub const PARTICULATE_MATTER_PM10_CONCENTRATION: BleUuid = BleUuid::new(0x2bd7);

/// Bluetooth characteristic UUID.
pub const SULFUR_DIOXIDE_CONCENTRATION: BleUuid = BleUuid::new(0x2bd8);

/// Bluetooth characteristic UUID.
pub const SULFUR_HEXAFLUORIDE_CONCENTRATION: BleUuid = BleUuid::new(0x2bd9);

/// Bluetooth characteristic UUID.
pub const HEARING_AID_FEATURES: BleUuid = BleUuid::new(0x2bda);

/// Bluetooth characteristic UUID.
pub const HEARING_AID_PRESET_CONTROL_POINT: BleUuid = BleUuid::new(0x2bdb);

/// Bluetooth characteristic UUID.
pub const ACTIVE_PRESET_INDEX: BleUuid = BleUuid::new(0x2bdc);

/// Bluetooth characteristic UUID.
pub const STORED_HEALTH_OBSERVATIONS: BleUuid = BleUuid::new(0x2bdd);

/// Bluetooth characteristic UUID.
pub const FIXED_STRING_64: BleUuid = BleUuid::new(0x2bde);

/// Bluetooth characteristic UUID.
pub const HIGH_TEMPERATURE: BleUuid = BleUuid::new(0x2bdf);

/// Bluetooth characteristic UUID.
pub const HIGH_VOLTAGE: BleUuid = BleUuid::new(0x2be0);

/// Bluetooth characteristic UUID.
pub const LIGHT_DISTRIBUTION: BleUuid = BleUuid::new(0x2be1);

/// Bluetooth characteristic UUID.
pub const LIGHT_OUTPUT: BleUuid = BleUuid::new(0x2be2);

/// Bluetooth characteristic UUID.
pub const LIGHT_SOURCE_TYPE: BleUuid = BleUuid::new(0x2be3);

/// Bluetooth characteristic UUID.
pub const NOISE: BleUuid = BleUuid::new(0x2be4);

/// Bluetooth characteristic UUID.
pub const RELATIVE_RUNTIME_IN_A_CORRELATED_COLOR_TEMPERATURE_RANGE: BleUuid = BleUuid::new(0x2be5);

/// Bluetooth characteristic UUID.
pub const TIME_SECOND_32: BleUuid = BleUuid::new(0x2be6);

/// Bluetooth characteristic UUID.
pub const VOC_CONCENTRATION: BleUuid = BleUuid::new(0x2be7);

/// Bluetooth characteristic UUID.
pub const VOLTAGE_FREQUENCY: BleUuid = BleUuid::new(0x2be8);

/// Bluetooth characteristic UUID.
pub const BATTERY_CRITICAL_STATUS: BleUuid = BleUuid::new(0x2be9);

/// Bluetooth characteristic UUID.
pub const BATTERY_HEALTH_STATUS: BleUuid = BleUuid::new(0x2bea);

/// Bluetooth characteristic UUID.
pub const BATTERY_HEALTH_INFORMATION: BleUuid = BleUuid::new(0x2beb);

/// Bluetooth characteristic UUID.
pub const BATTERY_INFORMATION: BleUuid = BleUuid::new(0x2bec);

/// Bluetooth characteristic UUID.
pub const BATTERY_LEVEL_STATUS: BleUuid = BleUuid::new(0x2bed);

/// Bluetooth characteristic UUID.
pub const BATTERY_TIME_STATUS: BleUuid = BleUuid::new(0x2bee);

/// Bluetooth characteristic UUID.
pub const ESTIMATED_SERVICE_DATE: BleUuid = BleUuid::new(0x2bef);

/// Bluetooth characteristic UUID.
pub const BATTERY_ENERGY_STATUS: BleUuid = BleUuid::new(0x2bf0);

/// Bluetooth characteristic UUID.
pub const OBSERVATION_SCHEDULE_CHANGED: BleUuid = BleUuid::new(0x2bf1);

/// Bluetooth characteristic UUID.
pub const CURRENT_ELAPSED_TIME: BleUuid = BleUuid::new(0x2bf2);

/// Bluetooth characteristic UUID.
pub const HEALTH_SENSOR_FEATURES: BleUuid = BleUuid::new(0x2bf3);

/// Bluetooth characteristic UUID.
pub const GHS_CONTROL_POINT: BleUuid = BleUuid::new(0x2bf4);

/// Bluetooth characteristic UUID.
pub const LE_GATT_SECURITY_LEVELS: BleUuid = BleUuid::new(0x2bf5);

/// Bluetooth characteristic UUID.
pub const ESL_ADDRESS: BleUuid = BleUuid::new(0x2bf6);

/// Bluetooth characteristic UUID.
pub const AP_SYNC_KEY_MATERIAL: BleUuid = BleUuid::new(0x2bf7);

/// Bluetooth characteristic UUID.
pub const ESL_RESPONSE_KEY_MATERIAL: BleUuid = BleUuid::new(0x2bf8);

/// Bluetooth characteristic UUID.
pub const ESL_CURRENT_ABSOLUTE_TIME: BleUuid = BleUuid::new(0x2bf9);

/// Bluetooth characteristic UUID.
pub const ESL_DISPLAY_INFORMATION: BleUuid = BleUuid::new(0x2bfa);

/// Bluetooth characteristic UUID.
pub const ESL_IMAGE_INFORMATION: BleUuid = BleUuid::new(0x2bfb);

/// Bluetooth characteristic UUID.
pub const ESL_SENSOR_INFORMATION: BleUuid = BleUuid::new(0x2bfc);

/// Bluetooth characteristic UUID.
pub const ESL_LED_INFORMATION: BleUuid = BleUuid::new(0x2bfd);

/// Bluetooth characteristic UUID.
pub const ESL_CONTROL_POINT: BleUuid = BleUuid::new(0x2bfe);

/// Bluetooth characteristic UUID.
pub const UDI_FOR_MEDICAL_DEVICES: BleUuid = BleUuid::new(0x2bff);

/// Bluetooth characteristic UUID.
pub const GMAP_ROLE: BleUuid = BleUuid::new(0x2c00);

/// Bluetooth characteristic UUID.
pub const UGG_FEATURES: BleUuid = BleUuid::new(0x2c01);

/// Bluetooth characteristic UUID.
pub const UGT_FEATURES: BleUuid = BleUuid::new(0x2c02);

/// Bluetooth characteristic UUID.
pub const BGS_FEATURES: BleUuid = BleUuid::new(0x2c03);

/// Bluetooth characteristic UUID.
pub const BGR_FEATURES: BleUuid = BleUuid::new(0x2c04);

/// Bluetooth characteristic UUID.
pub const PERCENTAGE_8_STEPS: BleUuid = BleUuid::new(0x2c05);

/// Bluetooth characteristic UUID.
pub const ACCELERATION: BleUuid = BleUuid::new(0x2c06);

/// Bluetooth characteristic UUID.
pub const FORCE: BleUuid = BleUuid::new(0x2c07);

/// Bluetooth characteristic UUID.
pub const LINEAR_POSITION: BleUuid = BleUuid::new(0x2c08);

/// Bluetooth characteristic UUID.
pub const ROTATIONAL_SPEED: BleUuid = BleUuid::new(0x2c09);

/// Bluetooth characteristic UUID.
pub const LENGTH: BleUuid = BleUuid::new(0x2c0a);

/// Bluetooth characteristic UUID.
pub const TORQUE: BleUuid = BleUuid::new(0x2c0b);

/// Bluetooth characteristic UUID.
pub const IMD_STATUS: BleUuid = BleUuid::new(0x2c0c);

/// Bluetooth characteristic UUID.
pub const IMDS_DESCRIPTOR_VALUE_CHANGED: BleUuid = BleUuid::new(0x2c0d);

/// Bluetooth characteristic UUID.
pub const FIRST_USE_DATE: BleUuid = BleUuid::new(0x2c0e);

/// Bluetooth characteristic UUID.
pub const LIFE_CYCLE_DATA: BleUuid = BleUuid::new(0x2c0f);

/// Bluetooth characteristic UUID.
pub const WORK_CYCLE_DATA: BleUuid = BleUuid::new(0x2c10);

/// Bluetooth characteristic UUID.
pub const SERVICE_CYCLE_DATA: BleUuid = BleUuid::new(0x2c11);

/// Bluetooth characteristic UUID.
pub const IMD_CONTROL: BleUuid = BleUuid::new(0x2c12);

/// Bluetooth characteristic UUID.
pub const IMD_HISTORICAL_DATA: BleUuid = BleUuid::new(0x2c13);