//! UUIDs for the declarations module.

// This file is auto-generated by the update_uuids application.
// Based on https://bitbucket.org/bluetooth-SIG/public.git
// Commit hash: 22c4a7a751fe51de707be6d294adb0d115e86897

use super::BluetoothUuid16;

/// Bluetooth declarations UUID.
///
/// `0x2800` Primary Service
pub const PRIMARY_SERVICE: BluetoothUuid16 = BluetoothUuid16::new(0x2800);

/// Bluetooth declarations UUID.
///
/// `0x2801` Secondary Service
pub const SECONDARY_SERVICE: BluetoothUuid16 = BluetoothUuid16::new(0x2801);

/// Bluetooth declarations UUID.
///
/// `0x2802` Include
pub const INCLUDE: BluetoothUuid16 = BluetoothUuid16::new(0x2802);

/// Bluetooth declarations UUID.
///
/// `0x2803` Characteristic
pub const CHARACTERISTIC: BluetoothUuid16 = BluetoothUuid16::new(0x2803);
