//! UUIDs for the descriptors module.

// This file is auto-generated by the update_uuids application.
// Based on https://bitbucket.org/bluetooth-SIG/public.git

use super::BleUuid;

/// Bluetooth descriptors UUID.
pub const CHARACTERISTIC_EXTENDED_PROPERTIES: BleUuid = BleUuid::new(0x2900);

/// Bluetooth descriptors UUID.
pub const CHARACTERISTIC_USER_DESCRIPTION: BleUuid = BleUuid::new(0x2901);

/// Bluetooth descriptors UUID.
pub const CLIENT_CHARACTERISTIC_CONFIGURATION: BleUuid = BleUuid::new(0x2902);

/// Bluetooth descriptors UUID.
pub const SERVER_CHARACTERISTIC_CONFIGURATION: BleUuid = BleUuid::new(0x2903);

/// Bluetooth descriptors UUID.
pub const CHARACTERISTIC_PRESENTATION_FORMAT: BleUuid = BleUuid::new(0x2904);

/// Bluetooth descriptors UUID.
pub const CHARACTERISTIC_AGGREGATE_FORMAT: BleUuid = BleUuid::new(0x2905);

/// Bluetooth descriptors UUID.
pub const VALID_RANGE: BleUuid = BleUuid::new(0x2906);

/// Bluetooth descriptors UUID.
pub const EXTERNAL_REPORT_REFERENCE: BleUuid = BleUuid::new(0x2907);

/// Bluetooth descriptors UUID.
pub const REPORT_REFERENCE: BleUuid = BleUuid::new(0x2908);

/// Bluetooth descriptors UUID.
pub const NUMBER_OF_DIGITALS: BleUuid = BleUuid::new(0x2909);

/// Bluetooth descriptors UUID.
pub const VALUE_TRIGGER_SETTING: BleUuid = BleUuid::new(0x290a);

/// Bluetooth descriptors UUID.
pub const ENVIRONMENTAL_SENSING_CONFIGURATION: BleUuid = BleUuid::new(0x290b);

/// Bluetooth descriptors UUID.
pub const ENVIRONMENTAL_SENSING_MEASUREMENT: BleUuid = BleUuid::new(0x290c);

/// Bluetooth descriptors UUID.
pub const ENVIRONMENTAL_SENSING_TRIGGER_SETTING: BleUuid = BleUuid::new(0x290d);

/// Bluetooth descriptors UUID.
pub const TIME_TRIGGER_SETTING: BleUuid = BleUuid::new(0x290e);

/// Bluetooth descriptors UUID.
pub const COMPLETE_BR_EDR_TRANSPORT_BLOCK_DATA: BleUuid = BleUuid::new(0x290f);

/// Bluetooth descriptors UUID.
pub const OBSERVATION_SCHEDULE: BleUuid = BleUuid::new(0x2910);

/// Bluetooth descriptors UUID.
pub const VALID_RANGE_AND_ACCURACY: BleUuid = BleUuid::new(0x2911);

/// Bluetooth descriptors UUID.
pub const MEASUREMENT_DESCRIPTION: BleUuid = BleUuid::new(0x2912);

/// Bluetooth descriptors UUID.
pub const MANUFACTURER_LIMITS: BleUuid = BleUuid::new(0x2913);

/// Bluetooth descriptors UUID.
pub const PROCESS_TOLERANCES: BleUuid = BleUuid::new(0x2914);

/// Bluetooth descriptors UUID.
pub const IMD_TRIGGER_SETTING: BleUuid = BleUuid::new(0x2915);
