//! UUIDs for the descriptors module.

// This file is auto-generated by the update_uuids application.
// Based on https://bitbucket.org/bluetooth-SIG/public.git
// Commit hash: 22c4a7a751fe51de707be6d294adb0d115e86897

use super::BluetoothUuid16;

/// Bluetooth descriptors UUID.
///
/// `0x2900` Characteristic Extended Properties
pub const CHARACTERISTIC_EXTENDED_PROPERTIES: BluetoothUuid16 = BluetoothUuid16::new(0x2900);

/// Bluetooth descriptors UUID.
///
/// `0x2901` Characteristic User Description
pub const CHARACTERISTIC_USER_DESCRIPTION: BluetoothUuid16 = BluetoothUuid16::new(0x2901);

/// Bluetooth descriptors UUID.
///
/// `0x2902` Client Characteristic Configuration
pub const CLIENT_CHARACTERISTIC_CONFIGURATION: BluetoothUuid16 = BluetoothUuid16::new(0x2902);

/// Bluetooth descriptors UUID.
///
/// `0x2903` Server Characteristic Configuration
pub const SERVER_CHARACTERISTIC_CONFIGURATION: BluetoothUuid16 = BluetoothUuid16::new(0x2903);

/// Bluetooth descriptors UUID.
///
/// `0x2904` Characteristic Presentation Format
pub const CHARACTERISTIC_PRESENTATION_FORMAT: BluetoothUuid16 = BluetoothUuid16::new(0x2904);

/// Bluetooth descriptors UUID.
///
/// `0x2905` Characteristic Aggregate Format
pub const CHARACTERISTIC_AGGREGATE_FORMAT: BluetoothUuid16 = BluetoothUuid16::new(0x2905);

/// Bluetooth descriptors UUID.
///
/// `0x2906` Valid Range
pub const VALID_RANGE: BluetoothUuid16 = BluetoothUuid16::new(0x2906);

/// Bluetooth descriptors UUID.
///
/// `0x2907` External Report Reference
pub const EXTERNAL_REPORT_REFERENCE: BluetoothUuid16 = BluetoothUuid16::new(0x2907);

/// Bluetooth descriptors UUID.
///
/// `0x2908` Report Reference
pub const REPORT_REFERENCE: BluetoothUuid16 = BluetoothUuid16::new(0x2908);

/// Bluetooth descriptors UUID.
///
/// `0x2909` Number of Digitals
pub const NUMBER_OF_DIGITALS: BluetoothUuid16 = BluetoothUuid16::new(0x2909);

/// Bluetooth descriptors UUID.
///
/// `0x290a` Value Trigger Setting
pub const VALUE_TRIGGER_SETTING: BluetoothUuid16 = BluetoothUuid16::new(0x290a);

/// Bluetooth descriptors UUID.
///
/// `0x290b` Environmental Sensing Configuration
pub const ENVIRONMENTAL_SENSING_CONFIGURATION: BluetoothUuid16 = BluetoothUuid16::new(0x290b);

/// Bluetooth descriptors UUID.
///
/// `0x290c` Environmental Sensing Measurement
pub const ENVIRONMENTAL_SENSING_MEASUREMENT: BluetoothUuid16 = BluetoothUuid16::new(0x290c);

/// Bluetooth descriptors UUID.
///
/// `0x290d` Environmental Sensing Trigger Setting
pub const ENVIRONMENTAL_SENSING_TRIGGER_SETTING: BluetoothUuid16 = BluetoothUuid16::new(0x290d);

/// Bluetooth descriptors UUID.
///
/// `0x290e` Time Trigger Setting
pub const TIME_TRIGGER_SETTING: BluetoothUuid16 = BluetoothUuid16::new(0x290e);

/// Bluetooth descriptors UUID.
///
/// `0x290f` Complete BR-EDR Transport Block Data
pub const COMPLETE_BR_EDR_TRANSPORT_BLOCK_DATA: BluetoothUuid16 = BluetoothUuid16::new(0x290f);

/// Bluetooth descriptors UUID.
///
/// `0x2910` Observation Schedule
pub const OBSERVATION_SCHEDULE: BluetoothUuid16 = BluetoothUuid16::new(0x2910);

/// Bluetooth descriptors UUID.
///
/// `0x2911` Valid Range and Accuracy
pub const VALID_RANGE_AND_ACCURACY: BluetoothUuid16 = BluetoothUuid16::new(0x2911);

/// Bluetooth descriptors UUID.
///
/// `0x2912` Measurement Description
pub const MEASUREMENT_DESCRIPTION: BluetoothUuid16 = BluetoothUuid16::new(0x2912);

/// Bluetooth descriptors UUID.
///
/// `0x2913` Manufacturer Limits
pub const MANUFACTURER_LIMITS: BluetoothUuid16 = BluetoothUuid16::new(0x2913);

/// Bluetooth descriptors UUID.
///
/// `0x2914` Process Tolerances
pub const PROCESS_TOLERANCES: BluetoothUuid16 = BluetoothUuid16::new(0x2914);

/// Bluetooth descriptors UUID.
///
/// `0x2915` IMD Trigger Setting
pub const IMD_TRIGGER_SETTING: BluetoothUuid16 = BluetoothUuid16::new(0x2915);
