//! UUIDs for the descriptors module.

// This file is auto-generated by the update_uuids application.
// Based on https://bitbucket.org/bluetooth-SIG/public.git
// Commit hash: 43c96bbde30dc6937fba488adb22b6406e1b9cad

use super::BluetoothUuid16;

/// Bluetooth descriptors UUID. (0x2900)
pub const CHARACTERISTIC_EXTENDED_PROPERTIES: BluetoothUuid16 = BluetoothUuid16::new(0x2900);

/// Bluetooth descriptors UUID. (0x2901)
pub const CHARACTERISTIC_USER_DESCRIPTION: BluetoothUuid16 = BluetoothUuid16::new(0x2901);

/// Bluetooth descriptors UUID. (0x2902)
pub const CLIENT_CHARACTERISTIC_CONFIGURATION: BluetoothUuid16 = BluetoothUuid16::new(0x2902);

/// Bluetooth descriptors UUID. (0x2903)
pub const SERVER_CHARACTERISTIC_CONFIGURATION: BluetoothUuid16 = BluetoothUuid16::new(0x2903);

/// Bluetooth descriptors UUID. (0x2904)
pub const CHARACTERISTIC_PRESENTATION_FORMAT: BluetoothUuid16 = BluetoothUuid16::new(0x2904);

/// Bluetooth descriptors UUID. (0x2905)
pub const CHARACTERISTIC_AGGREGATE_FORMAT: BluetoothUuid16 = BluetoothUuid16::new(0x2905);

/// Bluetooth descriptors UUID. (0x2906)
pub const VALID_RANGE: BluetoothUuid16 = BluetoothUuid16::new(0x2906);

/// Bluetooth descriptors UUID. (0x2907)
pub const EXTERNAL_REPORT_REFERENCE: BluetoothUuid16 = BluetoothUuid16::new(0x2907);

/// Bluetooth descriptors UUID. (0x2908)
pub const REPORT_REFERENCE: BluetoothUuid16 = BluetoothUuid16::new(0x2908);

/// Bluetooth descriptors UUID. (0x2909)
pub const NUMBER_OF_DIGITALS: BluetoothUuid16 = BluetoothUuid16::new(0x2909);

/// Bluetooth descriptors UUID. (0x290a)
pub const VALUE_TRIGGER_SETTING: BluetoothUuid16 = BluetoothUuid16::new(0x290a);

/// Bluetooth descriptors UUID. (0x290b)
pub const ENVIRONMENTAL_SENSING_CONFIGURATION: BluetoothUuid16 = BluetoothUuid16::new(0x290b);

/// Bluetooth descriptors UUID. (0x290c)
pub const ENVIRONMENTAL_SENSING_MEASUREMENT: BluetoothUuid16 = BluetoothUuid16::new(0x290c);

/// Bluetooth descriptors UUID. (0x290d)
pub const ENVIRONMENTAL_SENSING_TRIGGER_SETTING: BluetoothUuid16 = BluetoothUuid16::new(0x290d);

/// Bluetooth descriptors UUID. (0x290e)
pub const TIME_TRIGGER_SETTING: BluetoothUuid16 = BluetoothUuid16::new(0x290e);

/// Bluetooth descriptors UUID. (0x290f)
pub const COMPLETE_BR_EDR_TRANSPORT_BLOCK_DATA: BluetoothUuid16 = BluetoothUuid16::new(0x290f);

/// Bluetooth descriptors UUID. (0x2910)
pub const OBSERVATION_SCHEDULE: BluetoothUuid16 = BluetoothUuid16::new(0x2910);

/// Bluetooth descriptors UUID. (0x2911)
pub const VALID_RANGE_AND_ACCURACY: BluetoothUuid16 = BluetoothUuid16::new(0x2911);

/// Bluetooth descriptors UUID. (0x2912)
pub const MEASUREMENT_DESCRIPTION: BluetoothUuid16 = BluetoothUuid16::new(0x2912);

/// Bluetooth descriptors UUID. (0x2913)
pub const MANUFACTURER_LIMITS: BluetoothUuid16 = BluetoothUuid16::new(0x2913);

/// Bluetooth descriptors UUID. (0x2914)
pub const PROCESS_TOLERANCES: BluetoothUuid16 = BluetoothUuid16::new(0x2914);

/// Bluetooth descriptors UUID. (0x2915)
pub const IMD_TRIGGER_SETTING: BluetoothUuid16 = BluetoothUuid16::new(0x2915);
