//! UUIDs for the mesh profile module.

// This file is auto-generated by the update_uuids application.
// Based on https://bitbucket.org/bluetooth-SIG/public.git

use super::BleUuid;

/// Bluetooth mesh profile UUID.
pub const AMBIENT_LIGHT_SENSOR_NLC_PROFILE_10: BleUuid = BleUuid::new(0x1600);

/// Bluetooth mesh profile UUID.
pub const BASIC_LIGHTNESS_CONTROLLER_NLC_PROFILE_10: BleUuid = BleUuid::new(0x1601);

/// Bluetooth mesh profile UUID.
pub const BASIC_SCENE_SELECTOR_NLC_PROFILE_10: BleUuid = BleUuid::new(0x1602);

/// Bluetooth mesh profile UUID.
pub const DIMMING_CONTROL_NLC_PROFILE_10: BleUuid = BleUuid::new(0x1603);

/// Bluetooth mesh profile UUID.
pub const ENERGY_MONITOR_NLC_PROFILE_10: BleUuid = BleUuid::new(0x1604);

/// Bluetooth mesh profile UUID.
pub const OCCUPANCY_SENSOR_NLC_PROFILE_10: BleUuid = BleUuid::new(0x1605);
