//! UUIDs for the mesh profile module.

// This file is auto-generated by the update_uuids application.
// Based on https://bitbucket.org/bluetooth-SIG/public.git
// Commit hash: 43c96bbde30dc6937fba488adb22b6406e1b9cad

use super::BluetoothUuid16;

/// Bluetooth mesh profile UUID. (0x1600)
pub const AMBIENT_LIGHT_SENSOR_NLC_PROFILE_10: BluetoothUuid16 = BluetoothUuid16::new(0x1600);

/// Bluetooth mesh profile UUID. (0x1601)
pub const BASIC_LIGHTNESS_CONTROLLER_NLC_PROFILE_10: BluetoothUuid16 = BluetoothUuid16::new(0x1601);

/// Bluetooth mesh profile UUID. (0x1602)
pub const BASIC_SCENE_SELECTOR_NLC_PROFILE_10: BluetoothUuid16 = BluetoothUuid16::new(0x1602);

/// Bluetooth mesh profile UUID. (0x1603)
pub const DIMMING_CONTROL_NLC_PROFILE_10: BluetoothUuid16 = BluetoothUuid16::new(0x1603);

/// Bluetooth mesh profile UUID. (0x1604)
pub const ENERGY_MONITOR_NLC_PROFILE_10: BluetoothUuid16 = BluetoothUuid16::new(0x1604);

/// Bluetooth mesh profile UUID. (0x1605)
pub const OCCUPANCY_SENSOR_NLC_PROFILE_10: BluetoothUuid16 = BluetoothUuid16::new(0x1605);
