//! UUIDs for the mesh profile module.

// This file is auto-generated by the update_uuids application.
// Based on https://bitbucket.org/bluetooth-SIG/public.git
// Commit hash: eb1a12af13e1c77d16dcb239ade4065b06e93907

use super::BluetoothUuid16;

/// Bluetooth mesh profile UUID.
///
/// `0x1600` Ambient Light Sensor NLC Profile 1.0
pub const AMBIENT_LIGHT_SENSOR_NLC_PROFILE_10: BluetoothUuid16 = BluetoothUuid16::new(0x1600);

/// Bluetooth mesh profile UUID.
///
/// `0x1601` Basic Lightness Controller NLC Profile 1.0
pub const BASIC_LIGHTNESS_CONTROLLER_NLC_PROFILE_10: BluetoothUuid16 = BluetoothUuid16::new(0x1601);

/// Bluetooth mesh profile UUID.
///
/// `0x1602` Basic Scene Selector NLC Profile 1.0
pub const BASIC_SCENE_SELECTOR_NLC_PROFILE_10: BluetoothUuid16 = BluetoothUuid16::new(0x1602);

/// Bluetooth mesh profile UUID.
///
/// `0x1603` Dimming Control NLC Profile 1.0
pub const DIMMING_CONTROL_NLC_PROFILE_10: BluetoothUuid16 = BluetoothUuid16::new(0x1603);

/// Bluetooth mesh profile UUID.
///
/// `0x1604` Energy Monitor NLC Profile 1.0
pub const ENERGY_MONITOR_NLC_PROFILE_10: BluetoothUuid16 = BluetoothUuid16::new(0x1604);

/// Bluetooth mesh profile UUID.
///
/// `0x1605` Occupancy Sensor NLC Profile 1.0
pub const OCCUPANCY_SENSOR_NLC_PROFILE_10: BluetoothUuid16 = BluetoothUuid16::new(0x1605);
