//! UUIDs for the object types module.

// This file is auto-generated by the update_uuids application.
// Based on https://bitbucket.org/bluetooth-SIG/public.git

use super::BleUuid;

/// Bluetooth object types UUID.
pub const UNSPECIFIED: BleUuid = BleUuid::new(0x2aca);

/// Bluetooth object types UUID.
pub const DIRECTORY_LISTING: BleUuid = BleUuid::new(0x2acb);

/// Bluetooth object types UUID.
pub const MEDIA_PLAYER_ICON: BleUuid = BleUuid::new(0x2ba9);

/// Bluetooth object types UUID.
pub const TRACK_SEGMENT: BleUuid = BleUuid::new(0x2baa);

/// Bluetooth object types UUID.
pub const TRACK: BleUuid = BleUuid::new(0x2bab);

/// Bluetooth object types UUID.
pub const GROUP: BleUuid = BleUuid::new(0x2bac);
