//! UUIDs for the object types module.

// This file is auto-generated by the update_uuids application.
// Based on https://bitbucket.org/bluetooth-SIG/public.git
// Commit hash: 43c96bbde30dc6937fba488adb22b6406e1b9cad

use super::BluetoothUuid16;

/// Bluetooth object types UUID. 
///
/// `0x2aca` Unspecified
pub const UNSPECIFIED: BluetoothUuid16 = BluetoothUuid16::new(0x2aca);

/// Bluetooth object types UUID. 
///
/// `0x2acb` Directory Listing
pub const DIRECTORY_LISTING: BluetoothUuid16 = BluetoothUuid16::new(0x2acb);

/// Bluetooth object types UUID. 
///
/// `0x2ba9` Media Player Icon
pub const MEDIA_PLAYER_ICON: BluetoothUuid16 = BluetoothUuid16::new(0x2ba9);

/// Bluetooth object types UUID. 
///
/// `0x2baa` Track Segment
pub const TRACK_SEGMENT: BluetoothUuid16 = BluetoothUuid16::new(0x2baa);

/// Bluetooth object types UUID. 
///
/// `0x2bab` Track
pub const TRACK: BluetoothUuid16 = BluetoothUuid16::new(0x2bab);

/// Bluetooth object types UUID. 
///
/// `0x2bac` Group
pub const GROUP: BluetoothUuid16 = BluetoothUuid16::new(0x2bac);
