//! UUIDs for the units module.

// This file is auto-generated by the update_uuids application.
// Based on https://bitbucket.org/bluetooth-SIG/public.git
// Commit hash: 43c96bbde30dc6937fba488adb22b6406e1b9cad

use super::BluetoothUuid16;

/// Bluetooth units UUID. (0x2700)
pub const UNITLESS: BluetoothUuid16 = BluetoothUuid16::new(0x2700);

/// Bluetooth units UUID. (0x2701)
pub const LENGTH_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x2701);

/// Bluetooth units UUID. (0x2702)
pub const MASS_KILOGRAM: BluetoothUuid16 = BluetoothUuid16::new(0x2702);

/// Bluetooth units UUID. (0x2703)
pub const TIME_SECOND: BluetoothUuid16 = BluetoothUuid16::new(0x2703);

/// Bluetooth units UUID. (0x2704)
pub const ELECTRIC_CURRENT_AMPERE: BluetoothUuid16 = BluetoothUuid16::new(0x2704);

/// Bluetooth units UUID. (0x2705)
pub const THERMODYNAMIC_TEMPERATURE_KELVIN: BluetoothUuid16 = BluetoothUuid16::new(0x2705);

/// Bluetooth units UUID. (0x2706)
pub const AMOUNT_OF_SUBSTANCE_MOLE: BluetoothUuid16 = BluetoothUuid16::new(0x2706);

/// Bluetooth units UUID. (0x2707)
pub const LUMINOUS_INTENSITY_CANDELA: BluetoothUuid16 = BluetoothUuid16::new(0x2707);

/// Bluetooth units UUID. (0x2710)
pub const AREA_SQUARE_METRES: BluetoothUuid16 = BluetoothUuid16::new(0x2710);

/// Bluetooth units UUID. (0x2711)
pub const VOLUME_CUBIC_METRES: BluetoothUuid16 = BluetoothUuid16::new(0x2711);

/// Bluetooth units UUID. (0x2712)
pub const VELOCITY_METRES_PER_SECOND: BluetoothUuid16 = BluetoothUuid16::new(0x2712);

/// Bluetooth units UUID. (0x2713)
pub const ACCELERATION_METRES_PER_SECOND_SQUARED: BluetoothUuid16 = BluetoothUuid16::new(0x2713);

/// Bluetooth units UUID. (0x2714)
pub const WAVENUMBER_RECIPROCAL_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x2714);

/// Bluetooth units UUID. (0x2715)
pub const DENSITY_KILOGRAM_PER_CUBIC_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x2715);

/// Bluetooth units UUID. (0x2716)
pub const SURFACE_DENSITY_KILOGRAM_PER_SQUARE_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x2716);

/// Bluetooth units UUID. (0x2717)
pub const SPECIFIC_VOLUME_CUBIC_METRE_PER_KILOGRAM: BluetoothUuid16 = BluetoothUuid16::new(0x2717);

/// Bluetooth units UUID. (0x2718)
pub const CURRENT_DENSITY_AMPERE_PER_SQUARE_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x2718);

/// Bluetooth units UUID. (0x2719)
pub const MAGNETIC_FIELD_STRENGTH_AMPERE_PER_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x2719);

/// Bluetooth units UUID. (0x271a)
pub const AMOUNT_CONCENTRATION_MOLE_PER_CUBIC_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x271a);

/// Bluetooth units UUID. (0x271b)
pub const MASS_CONCENTRATION_KILOGRAM_PER_CUBIC_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x271b);

/// Bluetooth units UUID. (0x271c)
pub const LUMINANCE_CANDELA_PER_SQUARE_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x271c);

/// Bluetooth units UUID. (0x271d)
pub const REFRACTIVE_INDEX: BluetoothUuid16 = BluetoothUuid16::new(0x271d);

/// Bluetooth units UUID. (0x271e)
pub const RELATIVE_PERMEABILITY: BluetoothUuid16 = BluetoothUuid16::new(0x271e);

/// Bluetooth units UUID. (0x2720)
pub const PLANE_ANGLE_RADIAN: BluetoothUuid16 = BluetoothUuid16::new(0x2720);

/// Bluetooth units UUID. (0x2721)
pub const SOLID_ANGLE_STERADIAN: BluetoothUuid16 = BluetoothUuid16::new(0x2721);

/// Bluetooth units UUID. (0x2722)
pub const FREQUENCY_HERTZ: BluetoothUuid16 = BluetoothUuid16::new(0x2722);

/// Bluetooth units UUID. (0x2723)
pub const FORCE_NEWTON: BluetoothUuid16 = BluetoothUuid16::new(0x2723);

/// Bluetooth units UUID. (0x2724)
pub const PRESSURE_PASCAL: BluetoothUuid16 = BluetoothUuid16::new(0x2724);

/// Bluetooth units UUID. (0x2725)
pub const ENERGY_JOULE: BluetoothUuid16 = BluetoothUuid16::new(0x2725);

/// Bluetooth units UUID. (0x2726)
pub const POWER_WATT: BluetoothUuid16 = BluetoothUuid16::new(0x2726);

/// Bluetooth units UUID. (0x2727)
pub const ELECTRIC_CHARGE_COULOMB: BluetoothUuid16 = BluetoothUuid16::new(0x2727);

/// Bluetooth units UUID. (0x2728)
pub const ELECTRIC_POTENTIAL_DIFFERENCE_VOLT: BluetoothUuid16 = BluetoothUuid16::new(0x2728);

/// Bluetooth units UUID. (0x2729)
pub const CAPACITANCE_FARAD: BluetoothUuid16 = BluetoothUuid16::new(0x2729);

/// Bluetooth units UUID. (0x272a)
pub const ELECTRIC_RESISTANCE_OHM: BluetoothUuid16 = BluetoothUuid16::new(0x272a);

/// Bluetooth units UUID. (0x272b)
pub const ELECTRIC_CONDUCTANCE_SIEMENS: BluetoothUuid16 = BluetoothUuid16::new(0x272b);

/// Bluetooth units UUID. (0x272c)
pub const MAGNETIC_FLUX_WEBER: BluetoothUuid16 = BluetoothUuid16::new(0x272c);

/// Bluetooth units UUID. (0x272d)
pub const MAGNETIC_FLUX_DENSITY_TESLA: BluetoothUuid16 = BluetoothUuid16::new(0x272d);

/// Bluetooth units UUID. (0x272e)
pub const INDUCTANCE_HENRY: BluetoothUuid16 = BluetoothUuid16::new(0x272e);

/// Bluetooth units UUID. (0x272f)
pub const CELSIUS_TEMPERATURE_DEGREE_CELSIUS: BluetoothUuid16 = BluetoothUuid16::new(0x272f);

/// Bluetooth units UUID. (0x2730)
pub const LUMINOUS_FLUX_LUMEN: BluetoothUuid16 = BluetoothUuid16::new(0x2730);

/// Bluetooth units UUID. (0x2731)
pub const ILLUMINANCE_LUX: BluetoothUuid16 = BluetoothUuid16::new(0x2731);

/// Bluetooth units UUID. (0x2732)
pub const ACTIVITY_REFERRED_TO_A_RADIONUCLIDE_BECQUEREL: BluetoothUuid16 = BluetoothUuid16::new(0x2732);

/// Bluetooth units UUID. (0x2733)
pub const ABSORBED_DOSE_GRAY: BluetoothUuid16 = BluetoothUuid16::new(0x2733);

/// Bluetooth units UUID. (0x2734)
pub const DOSE_EQUIVALENT_SIEVERT: BluetoothUuid16 = BluetoothUuid16::new(0x2734);

/// Bluetooth units UUID. (0x2735)
pub const CATALYTIC_ACTIVITY_KATAL: BluetoothUuid16 = BluetoothUuid16::new(0x2735);

/// Bluetooth units UUID. (0x2740)
pub const DYNAMIC_VISCOSITY_PASCAL_SECOND: BluetoothUuid16 = BluetoothUuid16::new(0x2740);

/// Bluetooth units UUID. (0x2741)
pub const MOMENT_OF_FORCE_NEWTON_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x2741);

/// Bluetooth units UUID. (0x2742)
pub const SURFACE_TENSION_NEWTON_PER_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x2742);

/// Bluetooth units UUID. (0x2743)
pub const ANGULAR_VELOCITY_RADIAN_PER_SECOND: BluetoothUuid16 = BluetoothUuid16::new(0x2743);

/// Bluetooth units UUID. (0x2744)
pub const ANGULAR_ACCELERATION_RADIAN_PER_SECOND_SQUARED: BluetoothUuid16 = BluetoothUuid16::new(0x2744);

/// Bluetooth units UUID. (0x2745)
pub const HEAT_FLUX_DENSITY_WATT_PER_SQUARE_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x2745);

/// Bluetooth units UUID. (0x2746)
pub const HEAT_CAPACITY_JOULE_PER_KELVIN: BluetoothUuid16 = BluetoothUuid16::new(0x2746);

/// Bluetooth units UUID. (0x2747)
pub const SPECIFIC_HEAT_CAPACITY_JOULE_PER_KILOGRAM_KELVIN: BluetoothUuid16 = BluetoothUuid16::new(0x2747);

/// Bluetooth units UUID. (0x2748)
pub const SPECIFIC_ENERGY_JOULE_PER_KILOGRAM: BluetoothUuid16 = BluetoothUuid16::new(0x2748);

/// Bluetooth units UUID. (0x2749)
pub const THERMAL_CONDUCTIVITY_WATT_PER_METRE_KELVIN: BluetoothUuid16 = BluetoothUuid16::new(0x2749);

/// Bluetooth units UUID. (0x274a)
pub const ENERGY_DENSITY_JOULE_PER_CUBIC_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x274a);

/// Bluetooth units UUID. (0x274b)
pub const ELECTRIC_FIELD_STRENGTH_VOLT_PER_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x274b);

/// Bluetooth units UUID. (0x274c)
pub const ELECTRIC_CHARGE_DENSITY_COULOMB_PER_CUBIC_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x274c);

/// Bluetooth units UUID. (0x274d)
pub const SURFACE_CHARGE_DENSITY_COULOMB_PER_SQUARE_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x274d);

/// Bluetooth units UUID. (0x274e)
pub const ELECTRIC_FLUX_DENSITY_COULOMB_PER_SQUARE_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x274e);

/// Bluetooth units UUID. (0x274f)
pub const PERMITTIVITY_FARAD_PER_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x274f);

/// Bluetooth units UUID. (0x2750)
pub const PERMEABILITY_HENRY_PER_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x2750);

/// Bluetooth units UUID. (0x2751)
pub const MOLAR_ENERGY_JOULE_PER_MOLE: BluetoothUuid16 = BluetoothUuid16::new(0x2751);

/// Bluetooth units UUID. (0x2752)
pub const MOLAR_ENTROPY_JOULE_PER_MOLE_KELVIN: BluetoothUuid16 = BluetoothUuid16::new(0x2752);

/// Bluetooth units UUID. (0x2753)
pub const EXPOSURE_COULOMB_PER_KILOGRAM: BluetoothUuid16 = BluetoothUuid16::new(0x2753);

/// Bluetooth units UUID. (0x2754)
pub const ABSORBED_DOSE_RATE_GRAY_PER_SECOND: BluetoothUuid16 = BluetoothUuid16::new(0x2754);

/// Bluetooth units UUID. (0x2755)
pub const RADIANT_INTENSITY_WATT_PER_STERADIAN: BluetoothUuid16 = BluetoothUuid16::new(0x2755);

/// Bluetooth units UUID. (0x2756)
pub const RADIANCE_WATT_PER_SQUARE_METRE_STERADIAN: BluetoothUuid16 = BluetoothUuid16::new(0x2756);

/// Bluetooth units UUID. (0x2757)
pub const CATALYTIC_ACTIVITY_CONCENTRATION_KATAL_PER_CUBIC_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x2757);

/// Bluetooth units UUID. (0x2760)
pub const TIME_MINUTE: BluetoothUuid16 = BluetoothUuid16::new(0x2760);

/// Bluetooth units UUID. (0x2761)
pub const TIME_HOUR: BluetoothUuid16 = BluetoothUuid16::new(0x2761);

/// Bluetooth units UUID. (0x2762)
pub const TIME_DAY: BluetoothUuid16 = BluetoothUuid16::new(0x2762);

/// Bluetooth units UUID. (0x2763)
pub const PLANE_ANGLE_DEGREE: BluetoothUuid16 = BluetoothUuid16::new(0x2763);

/// Bluetooth units UUID. (0x2764)
pub const PLANE_ANGLE_MINUTE: BluetoothUuid16 = BluetoothUuid16::new(0x2764);

/// Bluetooth units UUID. (0x2765)
pub const PLANE_ANGLE_SECOND: BluetoothUuid16 = BluetoothUuid16::new(0x2765);

/// Bluetooth units UUID. (0x2766)
pub const AREA_HECTARE: BluetoothUuid16 = BluetoothUuid16::new(0x2766);

/// Bluetooth units UUID. (0x2767)
pub const VOLUME_LITRE: BluetoothUuid16 = BluetoothUuid16::new(0x2767);

/// Bluetooth units UUID. (0x2768)
pub const MASS_TONNE: BluetoothUuid16 = BluetoothUuid16::new(0x2768);

/// Bluetooth units UUID. (0x2780)
pub const PRESSURE_BAR: BluetoothUuid16 = BluetoothUuid16::new(0x2780);

/// Bluetooth units UUID. (0x2781)
pub const PRESSURE_MILLIMETRE_OF_MERCURY: BluetoothUuid16 = BluetoothUuid16::new(0x2781);

/// Bluetooth units UUID. (0x2782)
pub const LENGTH_ANGSTROM: BluetoothUuid16 = BluetoothUuid16::new(0x2782);

/// Bluetooth units UUID. (0x2783)
pub const LENGTH_NAUTICAL_MILE: BluetoothUuid16 = BluetoothUuid16::new(0x2783);

/// Bluetooth units UUID. (0x2784)
pub const AREA_BARN: BluetoothUuid16 = BluetoothUuid16::new(0x2784);

/// Bluetooth units UUID. (0x2785)
pub const VELOCITY_KNOT: BluetoothUuid16 = BluetoothUuid16::new(0x2785);

/// Bluetooth units UUID. (0x2786)
pub const LOGARITHMIC_RADIO_QUANTITY_NEPER: BluetoothUuid16 = BluetoothUuid16::new(0x2786);

/// Bluetooth units UUID. (0x2787)
pub const LOGARITHMIC_RADIO_QUANTITY_BEL: BluetoothUuid16 = BluetoothUuid16::new(0x2787);

/// Bluetooth units UUID. (0x27a0)
pub const LENGTH_YARD: BluetoothUuid16 = BluetoothUuid16::new(0x27a0);

/// Bluetooth units UUID. (0x27a1)
pub const LENGTH_PARSEC: BluetoothUuid16 = BluetoothUuid16::new(0x27a1);

/// Bluetooth units UUID. (0x27a2)
pub const LENGTH_INCH: BluetoothUuid16 = BluetoothUuid16::new(0x27a2);

/// Bluetooth units UUID. (0x27a3)
pub const LENGTH_FOOT: BluetoothUuid16 = BluetoothUuid16::new(0x27a3);

/// Bluetooth units UUID. (0x27a4)
pub const LENGTH_MILE: BluetoothUuid16 = BluetoothUuid16::new(0x27a4);

/// Bluetooth units UUID. (0x27a5)
pub const PRESSURE_POUND_FORCE_PER_SQUARE_INCH: BluetoothUuid16 = BluetoothUuid16::new(0x27a5);

/// Bluetooth units UUID. (0x27a6)
pub const VELOCITY_KILOMETRE_PER_HOUR: BluetoothUuid16 = BluetoothUuid16::new(0x27a6);

/// Bluetooth units UUID. (0x27a7)
pub const VELOCITY_MILE_PER_HOUR: BluetoothUuid16 = BluetoothUuid16::new(0x27a7);

/// Bluetooth units UUID. (0x27a8)
pub const ANGULAR_VELOCITY_REVOLUTION_PER_MINUTE: BluetoothUuid16 = BluetoothUuid16::new(0x27a8);

/// Bluetooth units UUID. (0x27a9)
pub const ENERGY_GRAM_CALORIE: BluetoothUuid16 = BluetoothUuid16::new(0x27a9);

/// Bluetooth units UUID. (0x27aa)
pub const ENERGY_KILOGRAM_CALORIE: BluetoothUuid16 = BluetoothUuid16::new(0x27aa);

/// Bluetooth units UUID. (0x27ab)
pub const ENERGY_KILOWATT_HOUR: BluetoothUuid16 = BluetoothUuid16::new(0x27ab);

/// Bluetooth units UUID. (0x27ac)
pub const THERMODYNAMIC_TEMPERATURE_DEGREE_FAHRENHEIT: BluetoothUuid16 = BluetoothUuid16::new(0x27ac);

/// Bluetooth units UUID. (0x27ad)
pub const PERCENTAGE: BluetoothUuid16 = BluetoothUuid16::new(0x27ad);

/// Bluetooth units UUID. (0x27ae)
pub const PER_MILLE: BluetoothUuid16 = BluetoothUuid16::new(0x27ae);

/// Bluetooth units UUID. (0x27af)
pub const PERIOD_BEATS_PER_MINUTE: BluetoothUuid16 = BluetoothUuid16::new(0x27af);

/// Bluetooth units UUID. (0x27b0)
pub const ELECTRIC_CHARGE_AMPERE_HOURS: BluetoothUuid16 = BluetoothUuid16::new(0x27b0);

/// Bluetooth units UUID. (0x27b1)
pub const MASS_DENSITY_MILLIGRAM_PER_DECILITRE: BluetoothUuid16 = BluetoothUuid16::new(0x27b1);

/// Bluetooth units UUID. (0x27b2)
pub const MASS_DENSITY_MILLIMOLE_PER_LITRE: BluetoothUuid16 = BluetoothUuid16::new(0x27b2);

/// Bluetooth units UUID. (0x27b3)
pub const TIME_YEAR: BluetoothUuid16 = BluetoothUuid16::new(0x27b3);

/// Bluetooth units UUID. (0x27b4)
pub const TIME_MONTH: BluetoothUuid16 = BluetoothUuid16::new(0x27b4);

/// Bluetooth units UUID. (0x27b5)
pub const CONCENTRATION_COUNT_PER_CUBIC_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x27b5);

/// Bluetooth units UUID. (0x27b6)
pub const IRRADIANCE_WATT_PER_SQUARE_METRE: BluetoothUuid16 = BluetoothUuid16::new(0x27b6);

/// Bluetooth units UUID. (0x27b7)
pub const MILLILITER_PER_KILOGRAM_PER_MINUTE: BluetoothUuid16 = BluetoothUuid16::new(0x27b7);

/// Bluetooth units UUID. (0x27b8)
pub const MASS_POUND: BluetoothUuid16 = BluetoothUuid16::new(0x27b8);

/// Bluetooth units UUID. (0x27b9)
pub const METABOLIC_EQUIVALENT: BluetoothUuid16 = BluetoothUuid16::new(0x27b9);

/// Bluetooth units UUID. (0x27ba)
pub const STEP_PER_MINUTE: BluetoothUuid16 = BluetoothUuid16::new(0x27ba);

/// Bluetooth units UUID. (0x27bc)
pub const STROKE_PER_MINUTE: BluetoothUuid16 = BluetoothUuid16::new(0x27bc);

/// Bluetooth units UUID. (0x27bd)
pub const PACE_KILOMETRE_PER_MINUTE: BluetoothUuid16 = BluetoothUuid16::new(0x27bd);

/// Bluetooth units UUID. (0x27be)
pub const LUMINOUS_EFFICACY_LUMEN_PER_WATT: BluetoothUuid16 = BluetoothUuid16::new(0x27be);

/// Bluetooth units UUID. (0x27bf)
pub const LUMINOUS_ENERGY_LUMEN_HOUR: BluetoothUuid16 = BluetoothUuid16::new(0x27bf);

/// Bluetooth units UUID. (0x27c0)
pub const LUMINOUS_EXPOSURE_LUX_HOUR: BluetoothUuid16 = BluetoothUuid16::new(0x27c0);

/// Bluetooth units UUID. (0x27c1)
pub const MASS_FLOW_GRAM_PER_SECOND: BluetoothUuid16 = BluetoothUuid16::new(0x27c1);

/// Bluetooth units UUID. (0x27c2)
pub const VOLUME_FLOW_LITRE_PER_SECOND: BluetoothUuid16 = BluetoothUuid16::new(0x27c2);

/// Bluetooth units UUID. (0x27c3)
pub const SOUND_PRESSURE_DECIBEL: BluetoothUuid16 = BluetoothUuid16::new(0x27c3);

/// Bluetooth units UUID. (0x27c4)
pub const PARTS_PER_MILLION: BluetoothUuid16 = BluetoothUuid16::new(0x27c4);

/// Bluetooth units UUID. (0x27c5)
pub const PARTS_PER_BILLION: BluetoothUuid16 = BluetoothUuid16::new(0x27c5);

/// Bluetooth units UUID. (0x27c6)
pub const MASS_DENSITY_RATE_MILLIGRAM_PER_DECILITRE_PER_MINUTE: BluetoothUuid16 = BluetoothUuid16::new(0x27c6);

/// Bluetooth units UUID. (0x27c7)
pub const ELECTRICAL_APPARENT_ENERGY_KILOVOLT_AMPERE_HOUR: BluetoothUuid16 = BluetoothUuid16::new(0x27c7);

/// Bluetooth units UUID. (0x27c8)
pub const ELECTRICAL_APPARENT_POWER_VOLT_AMPERE: BluetoothUuid16 = BluetoothUuid16::new(0x27c8);
