//! UUIDs for the units module.

// This file is auto-generated by the update_uuids application.
// Based on https://bitbucket.org/bluetooth-SIG/public.git

use super::BleUuid;

/// Bluetooth units UUID.
pub const UNITLESS: BleUuid = BleUuid::new(0x2700);

/// Bluetooth units UUID.
pub const LENGTH_METRE: BleUuid = BleUuid::new(0x2701);

/// Bluetooth units UUID.
pub const MASS_KILOGRAM: BleUuid = BleUuid::new(0x2702);

/// Bluetooth units UUID.
pub const TIME_SECOND: BleUuid = BleUuid::new(0x2703);

/// Bluetooth units UUID.
pub const ELECTRIC_CURRENT_AMPERE: BleUuid = BleUuid::new(0x2704);

/// Bluetooth units UUID.
pub const THERMODYNAMIC_TEMPERATURE_KELVIN: BleUuid = BleUuid::new(0x2705);

/// Bluetooth units UUID.
pub const AMOUNT_OF_SUBSTANCE_MOLE: BleUuid = BleUuid::new(0x2706);

/// Bluetooth units UUID.
pub const LUMINOUS_INTENSITY_CANDELA: BleUuid = BleUuid::new(0x2707);

/// Bluetooth units UUID.
pub const AREA_SQUARE_METRES: BleUuid = BleUuid::new(0x2710);

/// Bluetooth units UUID.
pub const VOLUME_CUBIC_METRES: BleUuid = BleUuid::new(0x2711);

/// Bluetooth units UUID.
pub const VELOCITY_METRES_PER_SECOND: BleUuid = BleUuid::new(0x2712);

/// Bluetooth units UUID.
pub const ACCELERATION_METRES_PER_SECOND_SQUARED: BleUuid = BleUuid::new(0x2713);

/// Bluetooth units UUID.
pub const WAVENUMBER_RECIPROCAL_METRE: BleUuid = BleUuid::new(0x2714);

/// Bluetooth units UUID.
pub const DENSITY_KILOGRAM_PER_CUBIC_METRE: BleUuid = BleUuid::new(0x2715);

/// Bluetooth units UUID.
pub const SURFACE_DENSITY_KILOGRAM_PER_SQUARE_METRE: BleUuid = BleUuid::new(0x2716);

/// Bluetooth units UUID.
pub const SPECIFIC_VOLUME_CUBIC_METRE_PER_KILOGRAM: BleUuid = BleUuid::new(0x2717);

/// Bluetooth units UUID.
pub const CURRENT_DENSITY_AMPERE_PER_SQUARE_METRE: BleUuid = BleUuid::new(0x2718);

/// Bluetooth units UUID.
pub const MAGNETIC_FIELD_STRENGTH_AMPERE_PER_METRE: BleUuid = BleUuid::new(0x2719);

/// Bluetooth units UUID.
pub const AMOUNT_CONCENTRATION_MOLE_PER_CUBIC_METRE: BleUuid = BleUuid::new(0x271a);

/// Bluetooth units UUID.
pub const MASS_CONCENTRATION_KILOGRAM_PER_CUBIC_METRE: BleUuid = BleUuid::new(0x271b);

/// Bluetooth units UUID.
pub const LUMINANCE_CANDELA_PER_SQUARE_METRE: BleUuid = BleUuid::new(0x271c);

/// Bluetooth units UUID.
pub const REFRACTIVE_INDEX: BleUuid = BleUuid::new(0x271d);

/// Bluetooth units UUID.
pub const RELATIVE_PERMEABILITY: BleUuid = BleUuid::new(0x271e);

/// Bluetooth units UUID.
pub const PLANE_ANGLE_RADIAN: BleUuid = BleUuid::new(0x2720);

/// Bluetooth units UUID.
pub const SOLID_ANGLE_STERADIAN: BleUuid = BleUuid::new(0x2721);

/// Bluetooth units UUID.
pub const FREQUENCY_HERTZ: BleUuid = BleUuid::new(0x2722);

/// Bluetooth units UUID.
pub const FORCE_NEWTON: BleUuid = BleUuid::new(0x2723);

/// Bluetooth units UUID.
pub const PRESSURE_PASCAL: BleUuid = BleUuid::new(0x2724);

/// Bluetooth units UUID.
pub const ENERGY_JOULE: BleUuid = BleUuid::new(0x2725);

/// Bluetooth units UUID.
pub const POWER_WATT: BleUuid = BleUuid::new(0x2726);

/// Bluetooth units UUID.
pub const ELECTRIC_CHARGE_COULOMB: BleUuid = BleUuid::new(0x2727);

/// Bluetooth units UUID.
pub const ELECTRIC_POTENTIAL_DIFFERENCE_VOLT: BleUuid = BleUuid::new(0x2728);

/// Bluetooth units UUID.
pub const CAPACITANCE_FARAD: BleUuid = BleUuid::new(0x2729);

/// Bluetooth units UUID.
pub const ELECTRIC_RESISTANCE_OHM: BleUuid = BleUuid::new(0x272a);

/// Bluetooth units UUID.
pub const ELECTRIC_CONDUCTANCE_SIEMENS: BleUuid = BleUuid::new(0x272b);

/// Bluetooth units UUID.
pub const MAGNETIC_FLUX_WEBER: BleUuid = BleUuid::new(0x272c);

/// Bluetooth units UUID.
pub const MAGNETIC_FLUX_DENSITY_TESLA: BleUuid = BleUuid::new(0x272d);

/// Bluetooth units UUID.
pub const INDUCTANCE_HENRY: BleUuid = BleUuid::new(0x272e);

/// Bluetooth units UUID.
pub const CELSIUS_TEMPERATURE_DEGREE_CELSIUS: BleUuid = BleUuid::new(0x272f);

/// Bluetooth units UUID.
pub const LUMINOUS_FLUX_LUMEN: BleUuid = BleUuid::new(0x2730);

/// Bluetooth units UUID.
pub const ILLUMINANCE_LUX: BleUuid = BleUuid::new(0x2731);

/// Bluetooth units UUID.
pub const ACTIVITY_REFERRED_TO_A_RADIONUCLIDE_BECQUEREL: BleUuid = BleUuid::new(0x2732);

/// Bluetooth units UUID.
pub const ABSORBED_DOSE_GRAY: BleUuid = BleUuid::new(0x2733);

/// Bluetooth units UUID.
pub const DOSE_EQUIVALENT_SIEVERT: BleUuid = BleUuid::new(0x2734);

/// Bluetooth units UUID.
pub const CATALYTIC_ACTIVITY_KATAL: BleUuid = BleUuid::new(0x2735);

/// Bluetooth units UUID.
pub const DYNAMIC_VISCOSITY_PASCAL_SECOND: BleUuid = BleUuid::new(0x2740);

/// Bluetooth units UUID.
pub const MOMENT_OF_FORCE_NEWTON_METRE: BleUuid = BleUuid::new(0x2741);

/// Bluetooth units UUID.
pub const SURFACE_TENSION_NEWTON_PER_METRE: BleUuid = BleUuid::new(0x2742);

/// Bluetooth units UUID.
pub const ANGULAR_VELOCITY_RADIAN_PER_SECOND: BleUuid = BleUuid::new(0x2743);

/// Bluetooth units UUID.
pub const ANGULAR_ACCELERATION_RADIAN_PER_SECOND_SQUARED: BleUuid = BleUuid::new(0x2744);

/// Bluetooth units UUID.
pub const HEAT_FLUX_DENSITY_WATT_PER_SQUARE_METRE: BleUuid = BleUuid::new(0x2745);

/// Bluetooth units UUID.
pub const HEAT_CAPACITY_JOULE_PER_KELVIN: BleUuid = BleUuid::new(0x2746);

/// Bluetooth units UUID.
pub const SPECIFIC_HEAT_CAPACITY_JOULE_PER_KILOGRAM_KELVIN: BleUuid = BleUuid::new(0x2747);

/// Bluetooth units UUID.
pub const SPECIFIC_ENERGY_JOULE_PER_KILOGRAM: BleUuid = BleUuid::new(0x2748);

/// Bluetooth units UUID.
pub const THERMAL_CONDUCTIVITY_WATT_PER_METRE_KELVIN: BleUuid = BleUuid::new(0x2749);

/// Bluetooth units UUID.
pub const ENERGY_DENSITY_JOULE_PER_CUBIC_METRE: BleUuid = BleUuid::new(0x274a);

/// Bluetooth units UUID.
pub const ELECTRIC_FIELD_STRENGTH_VOLT_PER_METRE: BleUuid = BleUuid::new(0x274b);

/// Bluetooth units UUID.
pub const ELECTRIC_CHARGE_DENSITY_COULOMB_PER_CUBIC_METRE: BleUuid = BleUuid::new(0x274c);

/// Bluetooth units UUID.
pub const SURFACE_CHARGE_DENSITY_COULOMB_PER_SQUARE_METRE: BleUuid = BleUuid::new(0x274d);

/// Bluetooth units UUID.
pub const ELECTRIC_FLUX_DENSITY_COULOMB_PER_SQUARE_METRE: BleUuid = BleUuid::new(0x274e);

/// Bluetooth units UUID.
pub const PERMITTIVITY_FARAD_PER_METRE: BleUuid = BleUuid::new(0x274f);

/// Bluetooth units UUID.
pub const PERMEABILITY_HENRY_PER_METRE: BleUuid = BleUuid::new(0x2750);

/// Bluetooth units UUID.
pub const MOLAR_ENERGY_JOULE_PER_MOLE: BleUuid = BleUuid::new(0x2751);

/// Bluetooth units UUID.
pub const MOLAR_ENTROPY_JOULE_PER_MOLE_KELVIN: BleUuid = BleUuid::new(0x2752);

/// Bluetooth units UUID.
pub const EXPOSURE_COULOMB_PER_KILOGRAM: BleUuid = BleUuid::new(0x2753);

/// Bluetooth units UUID.
pub const ABSORBED_DOSE_RATE_GRAY_PER_SECOND: BleUuid = BleUuid::new(0x2754);

/// Bluetooth units UUID.
pub const RADIANT_INTENSITY_WATT_PER_STERADIAN: BleUuid = BleUuid::new(0x2755);

/// Bluetooth units UUID.
pub const RADIANCE_WATT_PER_SQUARE_METRE_STERADIAN: BleUuid = BleUuid::new(0x2756);

/// Bluetooth units UUID.
pub const CATALYTIC_ACTIVITY_CONCENTRATION_KATAL_PER_CUBIC_METRE: BleUuid = BleUuid::new(0x2757);

/// Bluetooth units UUID.
pub const TIME_MINUTE: BleUuid = BleUuid::new(0x2760);

/// Bluetooth units UUID.
pub const TIME_HOUR: BleUuid = BleUuid::new(0x2761);

/// Bluetooth units UUID.
pub const TIME_DAY: BleUuid = BleUuid::new(0x2762);

/// Bluetooth units UUID.
pub const PLANE_ANGLE_DEGREE: BleUuid = BleUuid::new(0x2763);

/// Bluetooth units UUID.
pub const PLANE_ANGLE_MINUTE: BleUuid = BleUuid::new(0x2764);

/// Bluetooth units UUID.
pub const PLANE_ANGLE_SECOND: BleUuid = BleUuid::new(0x2765);

/// Bluetooth units UUID.
pub const AREA_HECTARE: BleUuid = BleUuid::new(0x2766);

/// Bluetooth units UUID.
pub const VOLUME_LITRE: BleUuid = BleUuid::new(0x2767);

/// Bluetooth units UUID.
pub const MASS_TONNE: BleUuid = BleUuid::new(0x2768);

/// Bluetooth units UUID.
pub const PRESSURE_BAR: BleUuid = BleUuid::new(0x2780);

/// Bluetooth units UUID.
pub const PRESSURE_MILLIMETRE_OF_MERCURY: BleUuid = BleUuid::new(0x2781);

/// Bluetooth units UUID.
pub const LENGTH_ANGSTROM: BleUuid = BleUuid::new(0x2782);

/// Bluetooth units UUID.
pub const LENGTH_NAUTICAL_MILE: BleUuid = BleUuid::new(0x2783);

/// Bluetooth units UUID.
pub const AREA_BARN: BleUuid = BleUuid::new(0x2784);

/// Bluetooth units UUID.
pub const VELOCITY_KNOT: BleUuid = BleUuid::new(0x2785);

/// Bluetooth units UUID.
pub const LOGARITHMIC_RADIO_QUANTITY_NEPER: BleUuid = BleUuid::new(0x2786);

/// Bluetooth units UUID.
pub const LOGARITHMIC_RADIO_QUANTITY_BEL: BleUuid = BleUuid::new(0x2787);

/// Bluetooth units UUID.
pub const LENGTH_YARD: BleUuid = BleUuid::new(0x27a0);

/// Bluetooth units UUID.
pub const LENGTH_PARSEC: BleUuid = BleUuid::new(0x27a1);

/// Bluetooth units UUID.
pub const LENGTH_INCH: BleUuid = BleUuid::new(0x27a2);

/// Bluetooth units UUID.
pub const LENGTH_FOOT: BleUuid = BleUuid::new(0x27a3);

/// Bluetooth units UUID.
pub const LENGTH_MILE: BleUuid = BleUuid::new(0x27a4);

/// Bluetooth units UUID.
pub const PRESSURE_POUND_FORCE_PER_SQUARE_INCH: BleUuid = BleUuid::new(0x27a5);

/// Bluetooth units UUID.
pub const VELOCITY_KILOMETRE_PER_HOUR: BleUuid = BleUuid::new(0x27a6);

/// Bluetooth units UUID.
pub const VELOCITY_MILE_PER_HOUR: BleUuid = BleUuid::new(0x27a7);

/// Bluetooth units UUID.
pub const ANGULAR_VELOCITY_REVOLUTION_PER_MINUTE: BleUuid = BleUuid::new(0x27a8);

/// Bluetooth units UUID.
pub const ENERGY_GRAM_CALORIE: BleUuid = BleUuid::new(0x27a9);

/// Bluetooth units UUID.
pub const ENERGY_KILOGRAM_CALORIE: BleUuid = BleUuid::new(0x27aa);

/// Bluetooth units UUID.
pub const ENERGY_KILOWATT_HOUR: BleUuid = BleUuid::new(0x27ab);

/// Bluetooth units UUID.
pub const THERMODYNAMIC_TEMPERATURE_DEGREE_FAHRENHEIT: BleUuid = BleUuid::new(0x27ac);

/// Bluetooth units UUID.
pub const PERCENTAGE: BleUuid = BleUuid::new(0x27ad);

/// Bluetooth units UUID.
pub const PER_MILLE: BleUuid = BleUuid::new(0x27ae);

/// Bluetooth units UUID.
pub const PERIOD_BEATS_PER_MINUTE: BleUuid = BleUuid::new(0x27af);

/// Bluetooth units UUID.
pub const ELECTRIC_CHARGE_AMPERE_HOURS: BleUuid = BleUuid::new(0x27b0);

/// Bluetooth units UUID.
pub const MASS_DENSITY_MILLIGRAM_PER_DECILITRE: BleUuid = BleUuid::new(0x27b1);

/// Bluetooth units UUID.
pub const MASS_DENSITY_MILLIMOLE_PER_LITRE: BleUuid = BleUuid::new(0x27b2);

/// Bluetooth units UUID.
pub const TIME_YEAR: BleUuid = BleUuid::new(0x27b3);

/// Bluetooth units UUID.
pub const TIME_MONTH: BleUuid = BleUuid::new(0x27b4);

/// Bluetooth units UUID.
pub const CONCENTRATION_COUNT_PER_CUBIC_METRE: BleUuid = BleUuid::new(0x27b5);

/// Bluetooth units UUID.
pub const IRRADIANCE_WATT_PER_SQUARE_METRE: BleUuid = BleUuid::new(0x27b6);

/// Bluetooth units UUID.
pub const MILLILITER_PER_KILOGRAM_PER_MINUTE: BleUuid = BleUuid::new(0x27b7);

/// Bluetooth units UUID.
pub const MASS_POUND: BleUuid = BleUuid::new(0x27b8);

/// Bluetooth units UUID.
pub const METABOLIC_EQUIVALENT: BleUuid = BleUuid::new(0x27b9);

/// Bluetooth units UUID.
pub const STEP_PER_MINUTE: BleUuid = BleUuid::new(0x27ba);

/// Bluetooth units UUID.
pub const STROKE_PER_MINUTE: BleUuid = BleUuid::new(0x27bc);

/// Bluetooth units UUID.
pub const PACE_KILOMETRE_PER_MINUTE: BleUuid = BleUuid::new(0x27bd);

/// Bluetooth units UUID.
pub const LUMINOUS_EFFICACY_LUMEN_PER_WATT: BleUuid = BleUuid::new(0x27be);

/// Bluetooth units UUID.
pub const LUMINOUS_ENERGY_LUMEN_HOUR: BleUuid = BleUuid::new(0x27bf);

/// Bluetooth units UUID.
pub const LUMINOUS_EXPOSURE_LUX_HOUR: BleUuid = BleUuid::new(0x27c0);

/// Bluetooth units UUID.
pub const MASS_FLOW_GRAM_PER_SECOND: BleUuid = BleUuid::new(0x27c1);

/// Bluetooth units UUID.
pub const VOLUME_FLOW_LITRE_PER_SECOND: BleUuid = BleUuid::new(0x27c2);

/// Bluetooth units UUID.
pub const SOUND_PRESSURE_DECIBEL: BleUuid = BleUuid::new(0x27c3);

/// Bluetooth units UUID.
pub const PARTS_PER_MILLION: BleUuid = BleUuid::new(0x27c4);

/// Bluetooth units UUID.
pub const PARTS_PER_BILLION: BleUuid = BleUuid::new(0x27c5);

/// Bluetooth units UUID.
pub const MASS_DENSITY_RATE_MILLIGRAM_PER_DECILITRE_PER_MINUTE: BleUuid = BleUuid::new(0x27c6);

/// Bluetooth units UUID.
pub const ELECTRICAL_APPARENT_ENERGY_KILOVOLT_AMPERE_HOUR: BleUuid = BleUuid::new(0x27c7);

/// Bluetooth units UUID.
pub const ELECTRICAL_APPARENT_POWER_VOLT_AMPERE: BleUuid = BleUuid::new(0x27c8);
